### ISSUE TITLE
Replication freeze when _change feed contains a doc which is no longer in _all_docs feed. "Tag: Replication Message: Got error NotFound"

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#531] opened 2015-11-25 10:58 UTC
Re-replicating to a device which tried to request a document listed in a _change feed that no longer exists (i.e. not in the _all_docs feed) results in the sync freezing and an error "Tag: Replication Message: Got error NotFound"

For more details on reproducing this issue etc. see another user experiencing this issue here:
https://forums.couchbase.com/t/change-feed--removed-flag-causing-issues-for-a-new-replication/5058

@borrrden Not sure if/how this relates to #527 or if they one in the same issue?

**Comment by borrrden** [comment] 2015-11-25 11:15
Looks like I missed your comment over there.  I believe this issue will be fixed when that one is.

**Comment by Steven-Mark-Ford** [comment] 2015-11-25 11:31
My concern is that, according to my current understanding, #527 will fix the issue going forward for users who do not yet have a _removed change set in their _changes feed. i.e. it will not resolve the issue for users who currently have the _removed change in their change feed (i.e. a corrupt feed)? I would expect the patch for this issue to resolve the issue going forward (#527) and the issue for existing users with a "corrupt" change feed. If this makes sense?

**Comment by Steven-Mark-Ford** [comment] 2015-11-25 11:35
@borrrden I was planning on looking into a fix for existing users, i.e those who already have a corrupt change feed, as a commit on a issue/531 branch. Not sure if you have any suggestions here or if this makes sense (considering what you had in mind for #527)?

**Comment by borrrden** [comment] 2015-11-25 11:38
There is really no such thing as a corrupt changes feed (if there were, that would be an issue for Sync Gateway).  The issue lies with how the client reacts to various types of entries in the feed.  So now I guess when the client comes across a `_removed` entry it doesn't know what to do and tries a few incorrect things.  What it really needs to do is ignore it and continue.  Any fix should work regardless of where the entry came in the changes feed (i.e. past or future).  

Any PRs are welcome as long as you have signed the new contributor agreement (the link is in the CONTRIBUTING.md document).  This was previously a problem on the iOS version (and is or was an issue on native Android) so the fix I am going to introduce will be identical.  You can see a link to the original issue from iOS at the top of #527

**Comment by borrrden** [comment] 2015-11-25 11:42
I see also that there might be an issue with handling 404 errors according to the original reports.  404 shouldn't stop the replication process.  I'll make sure it doesn't while I implement this change (the unit test I'm going to be porting from iOS should catch that).

**Comment by Steven-Mark-Ford** [comment] 2015-11-25 11:52
@borrrden Thanks! This is inline with what I had in-mind and I agree there is no such thing as an actual "corrupt" change feed. Was just confused with how #527 relates then, since according to the title ,#527 is dealing with "push replication" not "pull replication".

Thanks, I will sign the new contributor agreement and proceed with implementing a fix for the NotFound 404 scenario and simply update the replicator to continue/ignore in such scenarios.

**Comment by borrrden** [comment] 2015-11-25 11:57
I'll ask for some insight from the other leads on how they are handling this situation.  There is probably already a solution in place that simply hasn't made its way over here yet.

**Comment by Steven-Mark-Ford** [comment] 2015-11-25 14:03
@borrrden in the interim I need to roll out a patch to existing production users (i.e. a patch on 1.1.1.2 release as I don't want to include the other changes currently on master). What version of the various submodules were used at this point as it seems the submodules were not part of the repo on the 1.1.1.2 branch/tag?

**Comment by borrrden** [comment] 2015-11-25 14:06
I don't believe Android or Windows use any submodules for those targets at the version (unless you are building for .NET 3.5).  There are a few there for .NET 3.5 and Unity.

**Comment by borrrden** [comment] 2015-11-25 19:49
It's been a while since I reproduced this issue, and with the current master I can't seem to reproduce it anymore so it's possible I've already done something about this.

**Comment by Steven-Mark-Ford** [comment] 2015-12-03 08:35
@borrrden I think I've made some good progress on implementing a fix for this. I still need to run a few more tests on my local machine. 

Also getting a strange issue where when I restart replication it sometimes gets the whole change feed again, raising all change events again, which is not a huge issue as it does not re-download all the docs (due to the local _rev_diffs type check), but still not correct behavior. I just need to figure out if this is related to this issue or if it is a new issue.

Once I'm happy with the changes I will obviously need to apply my changes to the master and issue a pull request.

**Comment by borrrden** [comment] 2015-12-03 19:51
I'm having trouble reproducing this on the latest master.  Is there a certain test you are using to reproduce this?

**Comment by Steven-Mark-Ford** [comment] 2015-12-07 10:25
Not using a test case.
Just make sure the _changes feed references a document that is not in the _all_docs feed. You should then get a http NotFound returned and the replication will not continue. 

Easy to see this is still an issue on Master by looking at:
https://github.com/couchbase/couchbase-lite-net/blob/master/src/Couchbase.Lite.Shared/Replication.cs#L1360
i.e. the onCompletion logic is not called in this case.

**Comment by borrrden** [comment] 2015-12-07 15:04
I'm more interested in the steps required to get to that state.  I tried redoing the steps in the forum post but I don't get the wrong behavior.

**Comment by borrrden** [comment] 2016-01-12 03:38
@Steven-Mark-Ford After way too long of a period, this issue has gotten escalated I've finally understood what you mean about the onCompletion not being called in that instance.  I've also been able to pin down (thanks to lots of help from my colleagues) what could potentially cause this issue:

User1 exists with access to channel A
A document gets added into channel A, and then removed later
The same document gets updated further
The changes feed will contain a removed entry containing the revision ID of the document when the user lost access (i.e. a now defunct one)
The user starts the replication process over from the beginning again for whatever reason, and reaches that point in the changes feed
The replicator will request the document / revision combo in the removed entry, but the body might have been already thrown away by Couchbase Server (old revision bodies get expired and deleted)
In this case, sync gateway returns a 404 and the replication won't handle it correctly.  

I'll have a fix uploaded soon but I can imagine you already know what it is.

**Closed** 2016-01-14 23:02 UTC
Labels: bug, in progress, release-prep, size-small
