### ISSUE TITLE
ForestDB,1.3.1-16  net-windows-listener-client-sync-gateway-topology-specific failures

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#811] opened 2017-02-08 21:44 UTC
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway-topology-specific/38/console:
 
>       raise LiteServError("There should be no service running on the port")
E       LiteServError: There should be no service running on the port
 
>       client.delete_databases(ls_url)
E           HTTPError: 500 Server Error: Internal error for url: http://172.23.121.129:59840/ls_db
 
>           client.wait_for_replication_status_idle(ls_url, repl_id)
>               raise keywords.exceptions.TimeoutException("Wait for Replication Status Idle: TIMEOUT")
E               TimeoutException: Wait for Replication Status Idle: TIMEOUT

**Comment by borrrden** [comment] 2017-02-14 21:55
Duplicate of #816

**Closed by borrrden** 2017-02-14 21:55 UTC
