### ISSUE TITLE
Unable to get data from documents created throught SDK or directly on Couchbase server

### ISSUE THREAD

**Issue by adanl** [couchbase/couchbase-lite-net#1049] opened 2018-08-02 09:48 UTC
### Library Version

Couchbase.Lite 2.0.3

CouchbaseLite/2.0.3 (.NET; Microsoft Windows 10.0.17134 ) Build/2 LiteCore/ (905) Commit/0d4f930

### .NET Runtime

.NET Core 2.0 (Console Application)

### Operating System / Device Details

Windows 10 Enterprise 1803, Build 17134.165

### Log Output

No errors/exceptions

### Expected behavior

Get the Dictonary for synced documents.

### Actual behavior

The Dictonary is empty for synced documents. Dictonary only available for documents created locally on the Lite DB and that have not been altered on Couchbase Server.
As soon as a document that have been created on the Lite database is altered 

https://forums.couchbase.com/t/unable-to-get-data-from-documents-created-throught-sdk-or-directly-on-couchbasedb/17764

### Steps To Reproduce

I'm basically using the examples from https://developer.couchbase.com/documentation/mobile/2.0/couchbase-lite/csharp.html

### Reproduction Project

[Program.zip](https://github.com/couchbase/couchbase-lite-net/files/2252977/Program.zip)

**Comment by borrrden** [comment] 2018-08-03 03:35
Please post the sync gateway version and configuration as well for this

**Comment by adanl** [comment] 2018-08-03 10:38
2.0.0-832


[serviceconfig.zip](https://github.com/couchbase/couchbase-lite-net/files/2257044/serviceconfig.zip)

**Comment by borrrden** [comment] 2018-08-07 22:09
Oh one more important piece of information.  What version of Couchbase Server are you using?  It has to be 5.0+ in order for this to work.

**Comment by Sandychuang8** [comment] 2018-08-07 23:08
cannot reproduce the issue.

attemptted to repro using:
- .Net Core 2.0 console app
- Couchbase.Lite 2.0.3
- Sync Gateway 2.0.0-832

**Comment by adanl** [comment] 2018-08-08 06:54
Hi,

I'm using Couchbase Server Community Edition 5.1.1 build 5723.

Strange that you couldn't reproduce the issue. I will try to get hold of another computer to make sure that it isn't my environment that have the issue.

**Comment by adanl** [comment] 2018-08-08 09:46
Ok, i think i found something.

In the serviceconfig the account "TestUser" had access to the channel "*" through a role called Role_Full_Admin.
It seams like i'm not able to assign the user to the "*" channel that way (through a role). 

Adding following lines to config enables me to get the data:

"admin_channels": [
"*"
],

-Is it suppose to work this way? Not be able to assign the * channel from roles? And if i do not have access, why does it sync part of documents (The ID, Key and rev)?

Before adding above i wasn't able to go directly through the rest api either.
http://xx.xx.xx.xx:4984/test/Project::9a735a0e-9cb6-4596-9b3d-09735bd8d110

result:
{
error: "Forbidden",
reason: "forbidden"
}

**Comment by borrrden** [comment] 2018-08-08 11:04
@adamcfraser @bbrks Can either of you answer this?

**Comment by djpongh** [comment] 2018-08-08 21:33
also adding @tleyden

**Comment by bbrks** [comment] 2018-08-09 13:33
@adanl Can you get a list of channels that document belongs to? And also get the list of channels a user belongs to when the `*` channel is set via the `Role_Full_Admin` role.

Instructions to do this are described here: https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/channels/index.html#troubleshooting-channels

**Comment by adanl** [comment] 2018-08-22 21:00
Sorry for late reply,
Haven´t have time due to work and some other problems with my lab environment.

@bbrks  As soon as i´m up and running i send you the information!

Thanks!

**Comment by borrrden** [comment] 2018-11-01 10:43
@adanl It's been a while but have you gathered the information?  If not I will close this issue.

**Comment by djpongh** [comment] 2019-01-03 16:37
Closing.  @adanl, if you get the info requested, feel free to reopen.

**Closed by djpongh** 2019-01-03 16:37 UTC
Labels: P1: high, backlog, reproduce/investigate
