### ISSUE TITLE
System.UnauthorizedAccessException  while sending a Get request on  ip:port/db_name and some other Peer to Peer Sync Issues

### ISSUE THREAD

**Issue by SunilDhaker** [couchbase/couchbase-lite-net#435] opened 2015-06-19 07:01 UTC
CouchbaseLiteRouter: Unhandled non-Couchbase exception in routing logic
    System.UnauthorizedAccessException: Access to the path 'C:\Users\user\AppData\Local\Application Data' is denied.
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
       at System.IO.FileSystemEnumerableIterator`1.MoveNext()
       at Couchbase.Lite.Database.get_TotalDataSize()
       at Couchbase.Lite.Listener.DatabaseMethods.<GetConfiguration>c__AnonStorey0.<>m__0(Database db)
       at Couchbase.Lite.Listener.DatabaseMethods.PerformLogicWithDatabase(ICouchbaseListenerContext context, Boolean open, Func`2 action)
       at Couchbase.Lite.Listener.DatabaseMethods.GetConfiguration(ICouchbaseListenerContext context)
       at Couchbase.Lite.Listener.CouchbaseLiteRouter.HandleRequest(ICouchbaseListenerContext context)

Tried to track dawn the issue seems to be in this function(from Database.js) while calculating file 
```
   public long TotalDataSize {
            get {
                string dir = System.IO.Path.GetDirectoryName(Path);
                var info = new DirectoryInfo(dir);
                long size = 0;
                foreach (var fileInfo in info.EnumerateFiles("*", SearchOption.AllDirectories)) {
                    size += fileInfo.Length;
                }

                return size;
            }
        }
```
call trace is ==>  CouchbaseLiteRouter.cs line 156 > DatabaseMethod line 61 >  DatabaseMethod  line 520 > DatabaseMethod line 70

I also tried publishing app and running as administrator .
Already ran this command : netsh http add urlacl url=http://*:<PORT_YOU_CHOOSE>/ user=<DOMAIN>\<username>

<h1>Some other  issues<h1>  

<h3> issue 1 <h3>
When I tried to do a post on /db_name/  with document containing _id it creates a document but when I tried to post a document without _id value it gives following exception and this is also seen in replication log also  :

CouchbaseLiteRouter: Unhandled non-Couchbase exception in routing logic
    System.NullReferenceException: Object reference not set to an instance of an object.
       at DocumentMethods.UpdateDocument(ICouchbaseListenerContext context, Database db, String docId, Body body, Boolean deleting, Boolean allowConflict, RevisionInternal& outRev) in DocumentMethods.cs:line 320
       at DocumentMethods.UpdateDb(ICouchbaseListenerContext context, Database db, String docId, Body body, Boolean deleting) in DocumentMethods.cs:line 574
       at DocumentMethods.<>c__DisplayClassc.<CreateDocument>b__b(Database db, Body body) in DocumentMethods.cs:line 264
       at DocumentMethods.<>c__DisplayClass1e.<PerformLogicWithDocumentBody>b__1d(Database db) in DocumentMethods.cs:line 484
       at DatabaseMethods.PerformLogicWithDatabase(ICouchbaseListenerContext context, Boolean open, Func`2 action) in DatabaseMethods.cs:line 520
       at DocumentMethods.PerformLogicWithDocumentBody(ICouchbaseListenerContext context, Func`3 callback) in DocumentMethods.cs:line 473
       at DocumentMethods.CreateDocument(ICouchbaseListenerContext context) in DocumentMethods.cs:line 264
       at CouchbaseLiteRouter.HandleRequest(ICouchbaseListenerContext context) in CouchbaseLiteRouter.cs:line 156

And when I do a post request containing _id and _rev it geves ==>>  Couchbase.Lite.CouchbaseLiteException: No existing revision found with doc id

<h3> issue 2 <h3>

if I set a authenticator in replication it tries Url  db_name/_session/  which is not routed in router hence gives a exception 

<h3> issue 3 <h3>

When starting replication  if database contains some entries 

A first chance exception of type 'Couchbase.Lite.CouchbaseLiteException' occurred in Couch TODO.exe
CouchbaseLiteRouter: Couchbase exception in routing logic, this message can be ignored if intentional:
Couchbase.Lite.CouchbaseLiteException: Coucbase Lite error: BadId
   at CouchbaseListenerContext.get_DatabaseName() in CouchbaseListenerContext.cs:line 60
   at DatabaseMethods.PerformLogicWithDatabase(ICouchbaseListenerContext context, Boolean open, Func`2 action) inDatabaseMethods.cs:line 507
   at DatabaseMethods.GetConfiguration(ICouchbaseListenerContext context) inDatabaseMethods.cs:line 61
   at CouchbaseLiteRouter.HandleRequest(ICouchbaseListenerContext context) in CouchbaseLiteRouter.cs:line 156

and my Database name is valid its -->> "mydb"  I also tried other names .

<h3> issue 4 <h4>

any reuest with  /_local/  as endpoint is giving issue (I think router didn't handle that thing )

and I am always getting this 

The thread 0x1588 has exited with code 259 (0x103).
The thread 0x608 has exited with code 259 (0x103).
The thread 0x2140 has exited with code 259 (0x103).
The thread 0x78c has exited with code 259 (0x103).

**Comment by borrrden** [comment] 2015-06-19 07:19
This is a lot of information for one issue.  I need some more information about a few.

Could you show the code you are using for issues 2, 3, and 4?  Preferably in a separate ticket for each?  As far as #1 goes, the POST request without an _id is not a valid request.  And when you say "throw an exception" do you mean the listener throws an exception?  Or the client throws an exception because it doesn't receive a successful HTTP response?

**Comment by borrrden** [comment] 2015-06-19 08:56
Alright I have a little more information now.  I missed a null check in one place and that was the cause of issue 1.  However, the third case you mentioned (_id and _rev) sounds normal.  The _rev should be the latest id of the existing revision (the one being overwritten), not an id that you assign.  Couchbase Lite maintains full control over the revision IDs, and you cannot specify them.  

As for issue 2, I haven't implemented authentication with the replicator yet (as far as the released version goes).  It is on a branch right now, and I'll be putting it in soon though.  

Issue 3 and 4 I need more info about.

**Comment by SunilDhaker** [comment] 2015-06-19 10:08
Okea so I am able to reproduce case 1 as 

Device A running LiteListner ;
Device B  Does a OneShot replication(pull + push) with Device A ;

Case 1 :When A and B both have No documents I am getting an System.UnauthorizedAccessException on Device A (same log as I posted on top of this post )

Case 2 : When Only B has a Document again Only getting System.UnauthorizedAccessException on Device A and no sync .

Case 3 : When Device A have a document :  On Device A : System.UnauthorizedAccessException + System.NullReferenceException . 
Logs :: 
CouchbaseLiteRouter: Unhandled non-Couchbase exception in routing logic
    System.NullReferenceException: Object reference not set to an instance of an object.
       at Couchbase.Lite.Database.MultipartWriterForRev(RevisionInternal rev, String contentType) in Database.cs:line 2543
       at DocumentMethods.<>c__DisplayClass5.<GetDocument>b__4(Database db) inDocumentMethods.cs:line 127
       at DatabaseMethods.PerformLogicWithDatabase(ICouchbaseListenerContext context, Boolean open, Func`2 action) inDatabaseMethods.cs:line 520
       at DocumentMethods.GetDocument(ICouchbaseListenerContext context) inDocumentMethods.cs:line 60
       at CouchbaseLiteRouter.HandleRequest(ICouchbaseListenerContext context) inCouchbaseLiteRouter.cs:line 156

**Comment by SunilDhaker** [comment] 2015-06-19 10:16
I will  make new tickets as I reproduce 3 and 4 .

**Comment by SunilDhaker** [comment] 2015-06-19 10:30
Information on Issue 3 : So when I open this Url  http://192.168.3.231:59840/newdb1/location:97?rev=1-4f3067bbba658e951b178df93702ed1a&revs=true&attachments=true 

I get both System.NullReferenceException badId and when I do attachments=false I still get BadId(Logs same as issue 3) exception but I am able to get Document .

So Issue 3 is only reproducing with Browser only ,,,Replication is not reproducing it .

**Comment by borrrden** [comment] 2015-06-19 21:18
By the way are you running this as a web app or something?  What do you mean by "publishing" your app?

**Comment by SunilDhaker** [comment] 2015-06-19 21:24
I am running this as  WPF application .

**Comment by borrrden** [comment] 2015-06-19 23:16
With regards to the initial issue:  Is there anything special in your environment?  It looks like your computer either can't find the path in question or the user running the program doesn't have access to it.  Are you running as a user named "user" or are you setting up some kind of sandbox?

As for the third issue, it seems to be related to 431.  I made some fixes and committed them, and now I have a unit test that can successfully replicate documents to and from a listener (it includes the URL you describe).  Could you let me know how that affects your issues?  Also what is the status of the fourth issue with regards to _local documents?

**Comment by SunilDhaker** [comment] 2015-06-20 17:29
No I tried running on different machines . Two of my personal pc's running windows 8.1 and a windows 7 desktop .
Anyway for now I hardcoded  'TotalDataSize'  method to always return 0 as there is only one reference of the method in entire library.

After doing above changes in latest masterbrach code push replication is working fine but still pull replication doesn,t work . Also getting some other (I will give you more information on that after reproducing on another machine )


PS : I am testing this as making WPF C# .NET 4.5 application  on 2 windows 8.1 and a windows 7  machine .(couchbase libraries are referenced as shared project with latest master code) .

**Comment by SunilDhaker** [comment] 2015-06-20 17:35
And with latest code I am not able to reproduce issue 4 .

**Comment by borrrden** [comment] 2015-06-23 02:54
I will add logic to prevent that exception from crashing the listener, but the underlying cause is still mysterious to me.  The error means that when the listener attempts to write back to the client that the connection between the two does not exist.  

As for the UnauthorizedAccessException, I still believe there is something different about your machines vs mine because I can use that property without issue on three different platforms.  Can you check to see what the contents of that folder are in explorer, using the same user that you run the listener as?  Are there any files or folders in there that you cannot access?

**Comment by SunilDhaker** [comment] 2015-06-23 15:43
All database the files are in "C:\Users\sdhaker\AppData\Local"  or in C:\Users\sdhaker\AppData\Local\db_name attachment folder right ?

Okea so instead of 'SearchOption.AllDirectories' in latest code  using 'SearchOption.TopDirectoryOnly' solved the issue .


Some Info : 
I am not able to access folder "Application Data" in file explorer also . In CMD when I run command DIR  at path "C:\Users\sdhaker\AppData\Local" it doesn't list any directory name "Application Data" . 
But I can do cd "Application Data" and it navigates to that path . And running command DIR gives File not found .
 
So One theory behind the issue may be Application Data is System Reserved directory(or somethig which is not accessible or some Junction btwn path http://www.svrops.com/svrops/articles/jpoints.htm ) and EnumerateFiles finds this directory and when tries to access it gives exception .

**Comment by borrrden** [comment] 2015-06-23 21:20
The question is then why is it looking there.  The EnumerateFiles call will use the path of the database in question.  Can you put a breakpoint inside the property and examine the name of the database and the path?

**Comment by borrrden** [comment] 2015-07-03 04:48
@SunilDhaker Have you had a chance to look at what I mentioned in the last part of my comment?  If I don't hear anything soon I'll be closing this issue, so please be advised.

**Comment by SunilDhaker** [comment] 2015-07-03 06:02
Yes I did ,  Name of the database is same as I gave in manager (i.e mydb1) also path is "C:\Users\sdhaker\AppData\Local" .   

EnumerateFiles with SearchOption.AllDirectories  looks into all subdirectories for file starts with sanitizedName(which is same as database name) right ?

So "Application Data" is a subdirectory(or something else like Junction, I dont know) at databse path and as EnumerateFiles  tries to look into that directory it crashes as it donnt have permission to access that .

However SearchOption.TopDirectoryOnly working fine for me and feel free to close issue looks like  I am the only one who is getting this issue .

**Comment by borrrden** [comment] 2015-07-03 09:11
I see, so the issue is that it is trying to look in those directories for files as well.  I think I have an idea that will stop this from happening.  With your solution I don't think the attachments will be included in the total data size (the attachments are in a subfolder called "<dbname> attachments" which is why I wanted it to look recursively).  However, since that is the only one, I will just enumerate the files in it as well, and keep the TopDirectoryOnly intact.  That should take care of things.

**Comment by borrrden** [comment] 2015-07-04 01:19
Alright I've put in a fix into a branch called `issue/435` so check it out and see it if takes care of that.  It should, since it is similar to your fix.

**Comment by SunilDhaker** [comment] 2015-07-04 08:54
Yupp ! That worked :) . 

Please merge that in master , I am closing this as all issues has been fixed I think 

And thanks man for all your support !

**Closed** 2015-07-04 08:55 UTC
Labels: bug, in progress, P3: major, priority-low, size-medium
