### ISSUE TITLE
Could we have unitypackage

### ISSUE THREAD

**Issue by Thaina** [couchbase/couchbase-lite-net#1018] opened 2018-04-19 11:09 UTC
[As of unity 2018.1](https://blogs.unity3d.com/2018/03/28/updated-scripting-runtime-in-unity-2018-1-what-does-the-future-hold/) there are dotnet runtime 4.7 with netstandard 2.0

It seem possible to use this library in unity. Could you provide unitypackage for us?

**Comment by borrrden** [comment] 2018-04-19 11:17
I’m very glad that unity has finally achieved .net Standard but I don’t think we have the bandwidth to test and maintain a unity package. The good news is that it should be quite easy to support this as a community project and if you are interested I can point you to a blog post where I describe the process for incorporating a new platform. You have to implement a handful of simple classes and after that it should work.

**Comment by borrrden** [comment] 2018-08-28 08:43
[this](https://borrrden.wordpress.com/2017/06/27/lets-build-couchbase-lite-net-part-x-generic-platform/) is the blog post I mentioned. It was written quite a while ago but the same principle applies. 2.x is not, as you say, Xamarin only. It is a .NET Standard 2.0+ library with platform support packages. 90+% of the functionality is in the main library while the support library provides some context for how to log, how to find the default directory to work in, etc.  That is the piece that is needed to bring another platform to the table. You can see the real ones we use for the platforms we support in the various “support” directories under src. I’m typing this on a phone so it is a bit brief but I’m more than happy to help with technical aspects of this, we just can’t add it to our official platform list (mostly for support and legal reasons rather than technical ones).

**Comment by sabvdf** [comment] 2018-08-28 09:45
Ah, thanks, will let you know if and when I have it running and tested!

**Comment by sabvdf** [comment] 2018-08-29 10:43
Testing in latest Unity (2018.2.5f1) on latest macOS (10.13.6):
Only changing the framework for Support.NetDesktop to .Net Standard 2.0 indeed gives a dll Unity can use 👍
I can use local database and replication to remote SG 😄  but I can't close the replicator 😞. Somehow the `C4Socket.SocketOpened` delegate gets called when I call `Replicator.Close()`; and this leads to a native NULL pointer, apparently in one of the address strings.
After that an invalid refCount of -1, of course crashing Unity or the built application. I can't debug what object had the invalid the refCount, but I have been able to verify it comes from throwing this native error; if I comment out the catch block in `SocketFactory.SocketOpened` (in C4Socket.cs) the crash doesn't happen.

If I don't stop and dispose the replicator it works, but of course not totally: when I stop the execution and try to run the project again in the editor, I get "c4socket_registerFactory can only be called once" - but I guess that's logical...

Any ideas? (I could send you the projects if you want)

Here's the log (filtered):
```
12:19:44.254525| [Sync] ERROR: (WebSocketTransport) [27] Websocket Error: System.Exception: Error opening to socket ---> System.NullReferenceException: Object reference not set to an instance of an object
  at System.Text.UTF8Encoding.GetCharCount (System.Byte* bytes, System.Int32 count, System.Text.DecoderNLS baseDecoder) [0x000ff] in <f2e6809acb14476a81f399aeb800f8f2>:0 
  at System.String.CreateStringFromEncoding (System.Byte* bytes, System.Int32 byteLength, System.Text.Encoding encoding) [0x00000] in <f2e6809acb14476a81f399aeb800f8f2>:0 
  at System.Text.Encoding.GetString (System.Byte* bytes, System.Int32 byteCount) [0x00033] in <f2e6809acb14476a81f399aeb800f8f2>:0 
  at LiteCore.Interop.C4Slice.CreateString () [0x0000c] in /Users/sf/Documents/Projecten/couchbase-lite-net/src/LiteCore/src/LiteCore.Shared/Interop/C4Base.cs:122 
  at Couchbase.Lite.Sync.WebSocketTransport.DoOpen (LiteCore.Interop.C4Socket* socket, LiteCore.Interop.C4Address* address, LiteCore.Interop.C4Slice options, System.Void* context) [0x00000] in /Users/sf/Documents/Projecten/couchbase-lite-net/src/Couchbase.Lite.Shared/Sync/WebSocketTransport.cs:94 
  at (wrapper delegate-invoke) <Module>.invoke_void_C4Socket*_C4Address*_C4Slice_void*(LiteCore.Interop.C4Socket*,LiteCore.Interop.C4Address*,LiteCore.Interop.C4Slice,void*)
  at LiteCore.Interop.SocketFactory.SocketOpened (LiteCore.Interop.C4Socket* socket, LiteCore.Interop.C4Address* address, LiteCore.Interop.C4Slice options, System.Void* context) [0x0000a] in /Users/sf/Documents/Projecten/couchbase-lite-net/src/LiteCore/src/LiteCore.Shared/Interop/C4Socket.cs:153 
   --- End of inner exception stack trace ---
12:19:44.260537| [WS] WARNING: {C4SocketImpl#1}==> litecore::websocket::C4SocketImpl ws:(server address):4984/(db)/_blipsync
12:19:44.260675| [WS] WARNING: {C4SocketImpl#1} Unexpected or unclean socket disconnect! (reason=Unknown error, code=10)
12:19:44.260922| [Sync] ERROR: {Repl#2}==> litecore::repl::Replicator /Applications/Unity/Hub/Editor/2018.2.5f1/CouchbaseLite/(db).cblite2/ ->ws:(server address):4984/(db)/_blipsync
12:19:44.261041| [Sync] ERROR: {Repl#2} Got LiteCore error: unexpected exception (1/26)
12:19:44.261257| ERROR: RefCounted object at 0x1418b94a0 destructed while it had an invalid refCount of -1
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: RefCounted object at 0x1418b94a0 destructed while it had an invalid refCount of -1
```

**Comment by borrrden** [comment] 2018-08-30 00:04
> If I don't stop and dispose the replicator

How long are you waiting before disposing the replicator?  The stop process is asynchronous so disposing it too soon is likely to cause havoc.  Instead, you can safely dispose it once its status changed callback indicates that it is stopped.  Typing this I can see how that is not at all obvious so I will think about ways I can avoid it.  I'd much prefer to substitute a managed exception for a native crash!

**Comment by sabvdf** [comment] 2018-08-30 09:33
Unfortunately it's not so simple an oversight... I checked this.
I was of course expecting to have to wait with stopping until after it reported not busy anymore, and I also tried stopping a lot later, at application stop. Then to make sure there wasn't something else happening at application stop, I tied only the `Stop()` call (it wasn't Close() as I said earlier, that doesn't exist) to a button click so it was the only thing happening. Same exception.

Although just checking that log the exception resolves differently after the LiteCore error:
```
[Sync] ERROR: {Repl#2} Got LiteCore error: unexpected exception (1/26)
Receiving unhandled NULL exception
Obtained 0 stack frames.
Unity(66808,0x700009aab000) malloc: *** error for object 0x120f994c8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

So I'm quite sure that somehow the call to `Stop()` leads to `C4Socket.SocketOpened` being called with the wrong parameters. I didn't dig into your protocols, but I figured it might be correct that stopping the replicator opens a socket connection - it doesn't keep an open connection after syncing and it wants to tell the server it's disconnecting? But then still something goes wrong with the parameters there...

**Comment by sabvdf** [comment] 2018-09-01 11:46
I've had a little more time for this, and it appears the replicator wasn't working yet after all, it just reported to be not busy anymore...

Turned on all verbose logging and found that it isn't connecting because it can't find the native 'open' call?
```
13:42:34.556823| [BLIP]: {Connection#1}==> litecore::blip::Connection ->ws:(host):4984/(db)/_blipsync
13:42:34.556919| [BLIP]: {Connection#1} Opening connection...
13:42:34.557287| [Sync]: {Repl#2}==> litecore::repl::Replicator /Applications/Unity/Hub/Editor/2018.2.5f1/CouchbaseLite/(db).cblite2/ ->ws:(host):4984/(db)/_blipsync
13:42:34.557368| [Sync]: {Repl#2} Push=continuous, Pull=continuous, Options={{WS-Protocols:"BLIP_3+CBMobile_2", auth:{password:"********", type:"Basic", username:"(username)"}, headers:{User-Agent:"CouchbaseLite/0.0.0 (.NET; Unix 17.7.0.0) Build/0 LiteCore/ (905) Commit/d3dcb84"}}}
13:42:34.557633| WARNING: Caught exception in Actor: C4SocketFactory does not support 'open'
13:42:34.557728| [Sync]: {Repl#2} activityLevel=connecting: connectionState=1
13:42:34.564015| [Sync]: (Replicator) [1] Replicator[<*> ws://(host):4984/(db)] is Connecting, progress 0/0
13:42:34.564525| [Sync]: (Replicator) [1] Replicator[<*> ws://(host):4984/(db)] is Connecting, progress 0/0
```

I've tried compiling LiteCore in Xcode myself but native functions in the resulting dylib don't get found by Unity at all... going to try Windows first, next time I get around to this. Unless (hopefully) you have an idea what's going on here?

**Comment by borrrden** [comment] 2018-09-01 12:03
I’m currently out of the office for the next week and a half or so but that message means I think that it cannot find the callback methods to use with the replicator. As a sanity check I’d like to make sure that P/Invoke works and is allowed in Unity’s runtime.

**Comment by sabvdf** [comment] 2018-09-13 07:43
Hey, what does your P2: medium label mean? Sounds promising...

I've been trying to make a generic support DLL for Unity to use, but when I try to compile any of the support DLLs I have the problem that a lot of internal classes from the shared projects are inaccessible; if I add references to Couchbase.Lite.Shared and LiteCore.Shared a lot of inconsistencies between partial declarations show up so that doesn't seem like the way to go either... How do you compile e.g. the Support.NetDesktop DLL? What am I missing?

**Comment by sabvdf** [comment] 2018-09-14 09:37
I'm having the same issue, not connecting to the SG, in Windows, as I did on macOS (only I'm not able to catch Trace logs in Unity with a TraceListener, not sure why)...

If I add this in Unity for your sanity check:
```
[DllImport("LiteCore", CallingConvention = CallingConvention.Cdecl)]
public static extern int c4_getObjectCount();
```
and then call `Debug.Log(c4_getObjectCount());` after initing a database there's no error and the function neatly returns 2. So from Unity LiteCore functions can be called... I don't know what to do next, why "C4SocketFactory does not support 'open'" happens.

**Comment by sabvdf** [comment] 2018-09-15 11:58
@borrrden Do you think you'll be able to shed light on this anytime soon? I'd be happy to maintain and update the community based Unity package as soon as I know how to get it to work.
But otherwise we'll probably just drop Couchbase and go back to Redis... 😞

**Comment by borrrden** [comment] 2018-09-15 12:32
I had to deal with a bit of a crisis today so I didn't get a chance to respond to this.  I cannot find this message in the codebase anywhere.  Where are you getting the LiteCore build from?  If it is too old, then the C API won't line up.  Try the one in the latest 2.1 release.

**Comment by sabvdf** [comment] 2018-09-17 08:35
Yesss... `[Sync]: {Repl#4} Replication complete!`
Somehow something didn't work on 2.0.3 that does on 2.1.0 😄
It works on macOS now, I'll make sure everything happens in the right order including cleanup, and then going to try the other OSes.

To distribute the package, shall I open a GitHub repo and put an asset package on the Unity Asset Store, or do you plan to do that officially from Couchbase after all?

**Comment by borrrden** [comment] 2018-09-17 10:39
That somehow probably comes from the inconsistent C API. If the C API was different in 2.0.3 then the P/Invoke methods will be incorrect and cause very odd behavior. 

As far as packaging is concerned we have no plans to add any new platforms to our support list (the requirement is more than just being shown to work.  There are QE and support requirements that involve other teams etc). This will probably cause a complication if enterprise features are needed but at that point you will need to speak to someone other than me (someone from the sales and support department)

**Comment by sabvdf** [comment] 2018-09-17 11:20
I figured as much, so my follow-up question is if there is an objection to me putting up a community package on GitHub / Asset Store, if I clearly label it as unofficial and unsupported? Or do you have another preferred way to 'support a community project' as you described it earlier?

**Comment by borrrden** [comment] 2018-09-17 21:16
No, there is no problem with you doing that.  Marking it unofficial and unsupported is not a requirement either.  The CE version of Couchbase Lite (i.e. the one in this repo) is licensed under Apache 2.0 so even if I had an objection it wouldn't be valid ;).  

Support a community project for me means providing technical input and fielding questions for it, and is separate from actual "support" from our support team.

**Comment by sabvdf** [comment] 2018-09-22 11:54
Right, so for iOS and Android I'm afraid I'm running into the same old issue.
- I can't use the Support DLLs from NuGet because they refer to Xamarin DLLs, which means I have to build my own DLLs
- However, since your blog post it seems that the architecture of your support projects did change; support DLLs need to include the bindings to LiteCore and call `Service.Register<ILiteCore>()` and `<ILiteCoreRaw>` and `<IProxy>`. Those are `internal` so it's necessary to include the project in `InternalsVisibleTo` of Couchbase.Lite.
- If I do include the project in `InternalsVisibleTo` I get one step further but then when I add a reference to UnityEngine.dll, I get a conflict between that and Couchbase for a lot of Annotations from `JetBrains.Annotations` that are declared in both UnityEngine.dll and Annotations.cs in LiteCore.Shared.
Do you have any suggestions on how to prevent or circumvent these conflicts? I need Unity's DLL (as replacement for Xamarin's) to get the right system paths etc., but I can't remove Annotations.cs from LiteCore.Shared because the annotations are used all over Couchbase. It feels like removing them and adding a reference to UnityEngine everywhere the annotations are used isn't the right way because it would break the principle of shared projects; or do you think that would be the only way to go?

**Comment by sabvdf** [comment] 2018-09-23 19:10
I got it; by re-using the iOS project in your project, the conflicts did not come up - I'll have to look into the difference sometime but there was probably something wrong with the way I had the references set up. Now there was something weird going on when I used `Service.AutoRegister(typeof(iOS).Assembly);` but it works when registering the decency injections one by one :)
Next up, Android... should pose different challenges 🤷‍♂️ 😉

**Comment by sabvdf** [comment] 2018-09-24 13:42
**Done!**
I've set it up at https://github.com/virtualplaynl/couchbase-lite-unity
It includes a Unity Package. I haven't gotten around to UWP and Linux, but the rest works.
(@Thaina, not sure if you still wanted to try this but now you can)

I've just tested simple functionality, will go to implementing it in a project; Still figuring out how to do cleanup on exit properly. Getting a couple of issues, differing a bit per platform. Any tips, @borrrden?

**Comment by borrrden** [comment] 2018-09-26 23:53
I'm glad to see things are progressing!  What were you referring to with "Any tips" ?

**Comment by borrrden** [comment] 2018-11-06 12:02
Sorry that I never actually responded to this.  Usually when an app exits all its resources are forcibly cleaned up (I/O closed, memory released, etc).  I wouldn't expect you to need to do anything in particular.  If you mean during suspension, then it's advisable to stop all replication.  I guess you could follow the standard C# practice of disposing `IDisposable` items.  The network based ones would be the first on the list since they will take a little longer to die in the background.

**Comment by borrrden** [comment] 2019-06-01 00:00
Since this is being provided externally it doesn't look like there are any more action items here.  So I will close this.

**Closed by borrrden** 2019-06-01 00:00 UTC
Labels: icebox

**Comment by FreakTheMighty** [comment] 2021-07-22 19:36
I'm wondering if anything has changed in Unity or in couchbase to make official support easier to tackle? This would be an incredibly valuable project to have available in Unity. Also, while researching alternatives, I noticed that realm-net [just released Unity support](https://github.com/realm/realm-dotnet/releases). Is there anything to be learned from how they've adapted their project to Unity?

**Comment by FreakTheMighty** [comment] 2021-09-10 01:07
@borrrden apologies for bugging you on this. I think we've gotten to a similar place as @sabvdf - we've made a recent build of couchbase-lite-net for Unity and have it running. However, when we introduce a replicator the Unity Editor hangs the second time we hit "Play". I'm not sure how to gather more information about the cause of the hang, but based on @sabvdf comments, I think it has to do with `Stop` and `Dispose` not closing out the web socket connections.

Having the editor work once, then requiring a force quit will be a big usability issue when we go to use replication.

Any thoughts on how we could address the problem?

**Comment by borrrden** [comment] 2021-09-10 01:17
Well if you are unable to get more information about the source of the hang on your end, there is very little I am able to do on mine.  One gotcha that I'd like to remind of is that `Stop()` is an asynchronous process and that the replicator is not truly stopped until it's status changes to stopped.  Also note that it's been years since I've actively worked on this product, so I won't have much detailed knowledge about current events anymore.

**Comment by FreakTheMighty** [comment] 2021-09-10 01:49
Thanks for the quick response @borrrden. That’s totally reasonable, I’ll need to think through how to get more info out of unity.

I did see that Stop queues up code for execution, but I figured when it runs things should clean up and unblock. 

Perhaps I’ll follow up on the forum and see if anyone has any thoughts on how to debug this.

**Comment by borrrden** [comment] 2021-09-10 02:25
You are right, they will continue to execute and there should be no problem, but this environment is unknown to me.  I never actually worked with the Unity *editor* and so I don't know what the ramifications of pressing "stop" are (does it freeze all sockets it has open, or some other kind of shenanigans, etc?).  But above all, without the source of the freeze it's hard to make any reasonable guess about what is causing it.  Just like `Stop()`, `Start()` is also asynchronous and there is no reason that it should block anything.  If you are force quitting, it should be possible to make a core dump though.  The core dump should contain traces of threads, etc.

**Comment by FreakTheMighty** [comment] 2021-09-10 14:03
I think I've found a few small hints. If I attach to unity after its frozen we can see the main thread stuck in this below state.
![image](https://user-images.githubusercontent.com/247092/132865158-9bb43250-0c88-44f7-bfeb-b61775fc41c8.png)

Meanwhile, despite calling `Stop` on CBL, there are a number of threads still running. Seems somewhat related to this persons [question](https://forum.unity.com/threads/unity-not-responding-psynch_cvwait-after-reload-assemblies-when-running-a-child-thread-in-dll-c.1040644/) about how to properly close down threads in a DLL.

![image](https://user-images.githubusercontent.com/247092/132865262-083a0013-1279-4755-9d71-482e328a3b12.png)
