### ISSUE TITLE
ForestDB+Encryption,1.4-67  net-windows-listener-client-sync-gateway failures

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#813] opened 2017-02-08 21:47 UTC
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway/163/console:
 
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[True] ERROR
 
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[False] ERROR
 
testsuites/listener/shared/client_sg/test_replication.py::test_replication_with_multiple_client_dbs_and_single_sync_gateway_db (fixtures used: environment, setup_client_syncgateway_suite, setup_client_syncgateway_test)Build timed out (after 45 minutes). Marking the build as failed.

**Comment by borrrden** [comment] 2017-02-14 21:54
Duplicate of #816

**Closed by borrrden** 2017-02-14 21:54 UTC
