### ISSUE TITLE
Issue in accessing docs in Parallel for each loop

### ISSUE THREAD

**Issue by jereesh** [couchbase/couchbase-lite-net#478] opened 2015-08-03 03:54 UTC
I am seeing an issue when I try to update different documents using Parallel For Each loop,
I have a collection whose keys are the document names and values are again key value pairs (i.e an IDictionary<string, object> - I have used ConcurrentDictionary). When I tried to add the data in the Value to corresponding documents using a Parallel for each loop, I get the following exception
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
at Couchbase.Lite.Database.GetDocument(String id)
at Couchbase.Lite.Database.GetExistingDocument(String id).

Details are added in the link  http://stackoverflow.com/questions/31645918/couch-base-lite-index-out-of-range?noredirect=1#comment51428631_31645918

**Comment by borrrden** [comment] 2015-08-22 03:19
@jereesh I'm unable to reproduce this, but I have a fix in mind.  I have committed it to the `issue/478` branch.  Let me know if it helps.

**Comment by borrrden** [comment] 2015-09-02 00:08
@jereesh Has the issue helped correct things for you?  Let me know within 7 days.  If I don't hear anything then I will consider this issue closed.

**Closed** 2015-09-10 21:20 UTC
Labels: bug, in progress, size-medium, testneeded, verify
