### ISSUE TITLE
Unsaved attachment ContentType property throws NullReferenceException

### ISSUE THREAD

**Issue by jefflill** [couchbase/couchbase-lite-net#666] opened 2016-06-16 02:42 UTC
Couchbase.Lite v1.2.1.1

I create an unsaved document revision and add an attachment.  Then before saving the revision, I get the attachment and try to access the `ContentType `property.  The property throws a `NullReferenceException`.

Here's my test code:

```
[Fact]
public void Report_UnsavedAttachmentContentType()
{
    using (var db = Manager.SharedInstance.GetDatabase("wonky"))
    {
        var doc = db.CreateDocument();
        var unsaved = doc.CreateRevision();

        unsaved.SetAttachment("attach", "type", new byte[] { 0, 1, 2, 3, 4 });

        var attachment = unsaved.GetAttachment("attach");

        Assert.Equal("type", attachment.ContentType);  // <<--- Throws a NullReferenceException
    }
}

```

**Comment by jefflill** [comment] 2016-06-16 02:44
Ooooh, looks like this was assigned the Devil's issue number.  Hopefully there will be no bad luck for anyone! :)

**Comment by borrrden** [comment] 2016-06-16 22:37
The bane of my existence...NullReferenceException.  I'll add this test real quick and see what comes of it on master.

**Comment by borrrden** [comment] 2016-06-16 22:37
Out of curiosity have you signed our contributor agreement?  I feel like I should ask and have you do it if I am going to be using these tests you've made.

**Comment by borrrden** [comment] 2016-06-16 22:42
Note: Couldn't reproduce on master, but will tag it as a bug.  If you want, you can give this test a shot with the latest package on http://latestbuilds.hq.couchbase.com/couchbase-lite-net/

**Comment by jefflill** [comment] 2016-06-17 18:00
No, I haven't signed this but I'd be willing to.

--Jeff

**Comment by borrrden** [comment] 2016-06-17 23:24
Ok, it is located at http://review.couchbase.org/#/settings/agreements

You can use your Github account to sign in and sign it electronically.   Thanks again!

**Comment by borrrden** [comment] 2016-06-24 04:47
Closing as per my comment last week

**Closed** 2016-06-24 04:47 UTC
Labels: bug, size-small
