### ISSUE TITLE
Exception when calling GetDatabase()

### ISSUE THREAD

**Issue by Ermish** [couchbase/couchbase-lite-net#418] opened 2015-05-13 13:50 UTC
An exception is getting thrown when I call `GetDatabase` and either create a new database or get an existing database. I noticed if I switch the path, it will work for a few times, then crash again.

I've tried:
* Setting the project and solution to `x86` 
* The database name is lowercase with no symbols or numbers
* I have permissions to the directory and have tried alternatives
* Running VS in adminstrator mode and non-administrator mode

Excption message: 
`Unable to create a storage engine, fatal error`

Stack Trace:
```   at Couchbase.Lite.Database.Open()
   at Couchbase.Lite.Manager.GetDatabase(String name)```

Couchbase lite version: `1.0.4.1`

**Comment by Ermish** [comment] 2015-05-13 14:24
Here's how I'm creating the Manager:
`new Manager(myDirectory, Manager.DefaultOptions);`

Also tried: `Manager.SharedInstance`

The exception also occurs when I use `GetExistingDatabase()` as well.

Hope this helps!

**Comment by Ermish** [comment] 2015-05-13 17:54
I think I figured out!
I was naming the database `couchbaselite`. Once I switched this to a different name, it works. 

I will leave this open in case you want to investigate why this name causes an exception.

**Comment by zgramana** [comment] 2015-05-13 18:24
@Ermish thanks for the report and follow-up. Very puzzling. I wasn't able to reproduce on Mono (OS X), but we'll still look into it on Windows.

What version of Windows + .NET are you using?

**Comment by Ermish** [comment] 2015-05-13 18:27
@zgramana Windows 8.1 + .NET 4.5.2 (also tried 4.5)

**Comment by borrrden** [comment] 2015-05-15 23:33
@Ermish Perfect, I have a machine with that configuration.  I will look into it.

**Comment by borrrden** [comment] 2015-07-10 23:38
I was not able to reproduce this.  Perhaps it could have been that an invalid file with the same name was in the directory where Couchbase Lite was looking for the database.  Does this still happen with 1.1?  If so can you do two things:

1) Try using a manager with a different path
2) If the error still happens, post your logs

**Comment by Ermish** [comment] 2015-07-11 13:09
@borrrden I haven't had any issue since I changed the database name. 
I started with an empty directory each time and tried several locations to ensure there weren't any permission issues.

**Comment by borrrden** [comment] 2015-07-14 00:36
Well, in that case I'm going to close this issue, but ping me back if it happens again!

**Closed** 2015-07-14 00:36 UTC
Labels: bug, P4: minor, priority-low, size-small, testneeded
