### ISSUE TITLE
Slow operations when encryption is enabled

### ISSUE THREAD

**Issue by alexrainman** [couchbase/couchbase-lite-net#760] opened 2016-10-08 16:51 UTC
I am using ForestDB engine. Delete a simple document when encryption is enabled takes like 10 times longer.

**Comment by borrrden** [comment] 2016-10-10 22:21
Please state the platform on which this happens.  Also is this compared to SQLite with encryption or compared to ForestDB without encryption?

**Comment by alexrainman** [comment] 2016-10-10 22:38
Engine: ForestDB
Platform: Android
Comparing: deleting a document with encryption vs without

**Comment by borrrden** [comment] 2016-10-10 22:43
Ok I will add a performance test that uses encryption and check the results of that.  If I can reproduce it then I will most likely need to file an issue downstream since the ForestDB logic is written in C++ with a thin C -> C# binding layer.

**Comment by alexrainman** [comment] 2016-10-11 20:05
I found why operations are slow when you use encryption. SymmetricKey uses a default value of 64000 rounds when rounds parameter is not provided. I checked your code and it seems that rounds should be > 200. Using 201 keeps the operations fast. What's your recommendation for rounds having a good balance of security and performance?

**Comment by borrrden** [comment] 2016-10-11 22:17
The reason for choosing 64,000 was to keep it the same as the default value for SQLCipher , but I've found the NIST [recommends at least 10,000 rounds](https://pages.nist.gov/800-63-3/sp800-63b.html#sec5) as of August 2016.

**Comment by borrrden** [comment] 2016-10-11 23:14
Oh, I forgot to mention that it would be better to create the keys just once and then save them.  The raw byte data doesn't need to be derived every time.

**Comment by alexrainman** [comment] 2016-10-11 23:38
I used Keychain to save Key and Salt. Will do some test using 10k rounds. Thanks

**Comment by borrrden** [comment] 2016-10-25 01:54
@alexrainman What is the result of your testing?

**Comment by alexrainman** [comment] 2016-10-25 02:01
@borrrden excelent speed using 10k rounds :)

**Comment by borrrden** [comment] 2016-10-25 02:08
Ok, I will close this ticket then.  Thank you!

**Closed by borrrden** 2016-10-25 02:08 UTC
Labels: review

**Comment by alexrainman** [comment] 2016-10-25 02:21
@borrrden thank you :)
