### ISSUE TITLE
BulkDownloader HTTP request timeouts not properly handled

### ISSUE THREAD

**Issue by zgramana** [couchbase/couchbase-lite-net#356] opened 2014-11-21 19:07 UTC
Reported by `orionhansen` via [a post on our mobile forum](https://forums.couchbase.com/t/error-replicating-to-net-cb-lite-db-from-sync-gateway/2110):

Not sure what I'm doing wrong here, but I'm getting an exception thrown randomly when I try and sync through the sync gateway to my new Couchbase Lite database. During the replication process, I get an exception (only every 5k-10k rows, or about every 3-4 minutes):

```
{"Object reference not set to an instance of an object."}
[System.NullReferenceException]: {"Object reference not set to an instance of an object."}
Data: {System.Collections.ListDictionaryInternal}
HelpLink: null
HResult: -2147467261
InnerException: null
Message: "Object reference not set to an instance of an object."
Source: "Couchbase.Lite"
StackTrace: "   at Couchbase.Lite.Replicator.BulkDownloader.ExecuteRequest(HttpClient httpClient, HttpRequestMessage request)"
TargetSite: {Void ExecuteRequest(System.Net.Http.HttpClient, System.Net.Http.HttpRequestMessage)}
```
All of the records are actually loaded into memory as far as I can tell (I have an event handler for the replication.Pull event that logs them to a file/console). It takes about 15 minutes to run, but once these are loaded into memory, another error occurs. In the end, nothing get's written to the local lite database.
```
BulkDownloader: Unhandled Exception at Line 129 or 130
System.Threading.Tasks.TaskCanceledException: A task was canceled. Replication:  Progress: set error = System.Threading.Tasks.TaskCanceledException: A task was canceled. BulkDownloader: ExecuteRequest Exception: System.NullReferenceException: Object reference not set to an instance of an object. at couchbase.Lite.Replicator.BulkDownloader.ExecuteRequest(HttpClient httpClient, HttpRequestMessage request) Replication:  Progress: set error = System.NullReferenceException: Object reference not set to an instance of an object.
   at Couchbase.Lite.Replicator.BulkDownloader.ExecuteRequest(HttpClient httpClient, HttpRequestMessage request)
```
or
```
BulkDownloader
Response task timed out: System.Threading.Tasks.Task`1[System.Net.Http.HttpResponseMessage], Couchbase.Lite.Util.SingleThreadTaskScheduler BulkDownloader: ExecuteRequest Exception:
[HttpResponseException: StatusCode = RequestTimeout] Replication:  Progress: set error =
[HttpResponseException: StatusCode = RequestTimeout] BulkDownloader: ExecuteRequest Exception: System.NullReferenceException: Object reference not set to an instance of an object. at Couchbase.Lite.Replicator.BulkDownloader.ExecuteRequest(HttpClient httpClient, HttpRequestMessage request) Replication:  Progress: set error = System.NullReferenceException: Object reference not set to an instance of an object. at Couchbase.Lite.Replicator.BulkDownloader.ExecuteRequest(HttpClient httpClient, HttpRequestMessage request)
```
**Detail:**
I have a bucket with ~200k entries. Sync gateway is setup with a shadow bucket that is getting served out. I believe that is working because the shadow and original buckets match the document count and I don't see errors when I run the SG verbosely. I can query the sync gateway using the REST API and haven't had issues.

I'm running SyncGateway 1.0.3-81, Couchbase Lite from NuGet v1.0.0, Couchbase Server 3.0.1 EE.

**Comment by zgramana** [comment] 2015-03-06 23:07
Untested fix currently on the issue-356 branch.

**Comment by brettharrisonzya** [comment] 2015-03-20 17:16
I'm having a similar issue.  The replication never recovers after getting a timeout error.  To reproduce, I have a couchbase lite database that has about 40 documents to sync on initial app launch.  Most of these documents have 2 attachments (An image file and an audio file).  On iOS I set the Developer Tools -> Network link conditioner to 3G.

With these settings I often get the timeout.

I tested the 356 branch and the problem ws not resolved for me.

**Comment by zgramana** [comment] 2015-04-24 23:04
@borrrden will tackle this in the quick turnaround 1.1.1 release.

**Comment by brettharrisonzya** [comment] 2015-04-24 23:40
Some extra information.

When the app starts up fresh and requests the _changes from the sync_gateway since 0 (first sync).
I may get a list of changes with seq numbers like this: (example)

1
2
3
4

Let's say 1 and 2 are requested in a bulk download http request and 3 and 4 are requested in a separate request.

If the 1 and 2 request fails (time out, network errors, etc...) and 3 and 4 succeed, it is possible that 3 and 4 get added to the database before 1 and 2.

It is then possible for the app to restart at a later time and request the _changes since 4.  In this case it will never pull changes 1 and 2.

**Comment by borrrden** [comment] 2015-06-25 06:15
@brettharrisonzya Ok, I had a real good hard look at this, but I haven't found anything yet (other than how difficult it is to get a good test for this).  There is a measure in place to prevent what you describe from happening.  I wrote a unit test to test its functionality, and uploaded that to the issue/356 branch.  I also rebased the branch to bring it up to speed with master so if you have it locally please delete the branch and re pull it.  

There are two things that could happen:

1) The bulk get fails over the allowed number of times.  In this case, the LastError of the Puller will be set to Timeout or Canceled, depending on the alignment of the planets.  But the exception will not (or at least should not) be throw up to the calling program.

2) The bulk get eventually succeeds, and all is well.

If the bulk get is split into two requests, and the first fails while the second succeeds, the second requests' documents will be inserted, but the LastSequence will not be updated, so on the next request it will re-request all the changes since the LastSequence before the bulk get started (So, say it started from 0 and got the second half, the LastSequence will remain at 0 when the puller is finished).  It will then see that it already has some of these documents on the next run and not download those.  The LastSequence at that point will be the number after the first half, so the next time it runs it will again skip the documents it got on the second half of the original run and only get the new ones.  Phew...that's a long confusing paragraph but in a simple and slightly idiotic dialogue it looks like this:

Client: WTF has changed since 0?
Server: Well I have 0, 1, 2, 3, ... 14
Client: Hrmph, that's a lot....gimme 0-9
Server: BAAARRRRRFFFFFF!
Client: Huh?  I said gimme 0-9!!
Server:  BAARRRRRFFFFFFFF some more
Client:  Psh fine then, gimme 5-14
Server: Ok, here you go
Client: Thanks!  (mental note, I better retry from 0 next time)
...TIME PASSES...
Client: WTF has changed since 0?
Server: Well I have 0, 1, 2, 3, ... 14
Client: Hmmm, well I already have 5, 6, 7, 8, ... 14.  Gimme 0-4
Server:  Ok, here you go
Client: Thanks! (mental note, I finished through 4)
...TIME PASSES...
Client: WTF has changed since 5?
Server: Well I have 5, 6, 7, 8, ... 20
Client: Hmmm, well I already have 5, 6, 7, 8, ... 14, Gimme 15-20
Server: Ok, here you go
Client: Thanks! (mental note, I finished through 20)

If you can observe things not happening this way then let me know, and it will probably be hard but describe what you did before the mischief occurred.

**Comment by borrrden** [comment] 2015-07-03 04:50
@brettharrisonzya Are you able to reproduce the behavior you indicated in your last post?  If not, then I am going to consider this ticket closed until it starts acting up again.

**Comment by brettharrisonzya** [comment] 2015-07-13 16:55
You can close this.  I have not been able to reproduce it.

**Closed** 2015-07-14 00:20 UTC
Labels: bug, P3: major, peer review, priority-medium, size-medium
