### ISSUE TITLE
error at building for iOS with IL2CPP

### ISSUE THREAD

**Issue by heonio** [couchbase/couchbase-lite-net#428] opened 2015-06-09 06:47 UTC
[UnityDemo]
Uinty3d : 5.0.2f1 Personal
Project setting : Other setting -> Configuration -> Scripting Backend : IL2CPP
(for 64bit supprot http://blogs.unity3d.com/2014/11/20/apple-ios-64-bit-support-in-unity/, requirement for appstore)
And inspector of Plugins/SQLitePCL.raw.dll, switch to 'Editor'

I use couchbase lite for my game project and also got same error. I could not build iOS project from unity3d because of error like this. It could be matter of il2cpp but I can't figure it out. 

```
IL2CPP error for method 'System.Boolean System.Collections.Generic.DefaultComparer`1::System.Collections.IEqualityComparer.Equals(System.Object,System.Object)' in assembly '/Users/heon/Documents/Unity Projects/meoguri/Temp/StagingArea/Data/Managed/System.Xml.Linq.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.


IL2CPP error for method 'System.Boolean System.Collections.Generic.DefaultComparer`1::System.Collections.IEqualityComparer.Equals(System.Object,System.Object)' in assembly '/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/System.Xml.Linq.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.


Failed running /Applications/Unity/Unity.app/Contents/Frameworks/il2cpp/build/il2cpp.exe --copy-level=None --emit-null-checks --enable-array-bounds-check --extra-types.file="/Applications/Unity/Unity.app/Contents/Frameworks/il2cpp/il2cpp_default_extra_types.txt" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/Assembly-CSharp-firstpass.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/UnityEngine.UI.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/Couchbase.Lite.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/ICSharpCode.SharpZipLib.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/Newtonsoft.Json.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/Rackspace.Threading.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/System.Net.Http.Net35.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/System.Threading.Tasks.Net35.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/ugly_net35.dll" --assembly="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/SQLitePCL.raw.dll" --generatedcppdir="/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/il2cppOutput/il2cppOutput" --builder=none 

stdout:
IL2CPP error for method 'System.Boolean System.Collections.Generic.DefaultComparer`1::System.Collections.IEqualityComparer.Equals(System.Object,System.Object)' in assembly '/Users/heon/Documents/Unity Projects/couchbase-lite-net/samples/UnityDemo/Temp/StagingArea/Data/Managed/System.Xml.Linq.dll'
Additional information: Build a development build for more information. Exception of type 'System.Exception' was thrown.
stderr:

Unhandled Exception:
System.Exception: Exception of type 'System.Exception' was thrown.
  at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction (Unity.IL2CPP.Node node, Unity.IL2CPP.Common.CFG.InstructionBlock block, Mono.Cecil.Cil.Instruction ins) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive (Unity.IL2CPP.Node node) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodBodyWriter.Generate () [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodBody (Mono.Cecil.MethodReference method, Unity.IL2CPP.CppCodeWriter methodBodyWriter, Unity.IL2CPP.MetadataUsage metadataUseCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodDefinition (Mono.Cecil.MethodReference method) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethod (Mono.Cecil.MethodReference method, MethodWriteMode mode) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodAndWrappers (Mono.Cecil.MethodReference method, MethodWriteMode mode) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodDefinitions (System.Func`2 filter) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteMethodDefinitionsFor (Unity.IL2CPP.CppCodeWriter writer, System.Func`2 filter, Mono.Cecil.TypeReference type, Unity.IL2CPP.Metadata.VTableBuilder vTableBuilder, Mono.Cecil.AssemblyDefinition mscorlib, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles (NiceIO.NPath outputDirectory, System.String fileName, IEnumerable`1 typeList, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteGenerics (Unity.IL2CPP.GenericsCollection.InflatedCollection genericsCollection, IEnumerable`1 allTypeDefinitions, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.WriteGenerics (Unity.IL2CPP.GenericsCollection.InflatedCollection allGenerics, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection, IEnumerable`1 allTypeDefinitions) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.Apply () [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies (System.String[] assemblies, NiceIO.NPath outputDir) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Exception of type 'System.Exception' was thrown.
  at Unity.IL2CPP.MethodBodyWriter.ProcessInstruction (Unity.IL2CPP.Node node, Unity.IL2CPP.Common.CFG.InstructionBlock block, Mono.Cecil.Cil.Instruction ins) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodBodyWriter.GenerateCodeRecursive (Unity.IL2CPP.Node node) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodBodyWriter.Generate () [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodBody (Mono.Cecil.MethodReference method, Unity.IL2CPP.CppCodeWriter methodBodyWriter, Unity.IL2CPP.MetadataUsage metadataUseCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodDefinition (Mono.Cecil.MethodReference method) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethod (Mono.Cecil.MethodReference method, MethodWriteMode mode) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodAndWrappers (Mono.Cecil.MethodReference method, MethodWriteMode mode) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.MethodWriter.WriteMethodDefinitions (System.Func`2 filter) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteMethodDefinitionsFor (Unity.IL2CPP.CppCodeWriter writer, System.Func`2 filter, Mono.Cecil.TypeReference type, Unity.IL2CPP.Metadata.VTableBuilder vTableBuilder, Mono.Cecil.AssemblyDefinition mscorlib, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteMethodSourceFiles (NiceIO.NPath outputDirectory, System.String fileName, IEnumerable`1 typeList, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.SourceWriter.WriteGenerics (Unity.IL2CPP.GenericsCollection.InflatedCollection genericsCollection, IEnumerable`1 allTypeDefinitions, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.WriteGenerics (Unity.IL2CPP.GenericsCollection.InflatedCollection allGenerics, Unity.IL2CPP.StringLiterals.StringLiteralCollection stringLiteralCollection, IEnumerable`1 allTypeDefinitions) [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.Apply () [0x00000] in <filename unknown>:0 
  at Unity.IL2CPP.AssemblyConverter.ConvertAssemblies (System.String[] assemblies, NiceIO.NPath outputDir) [0x00000] in <filename unknown>:0 

UnityEngine.Debug:LogError(Object)
UnityEditorInternal.Runner:RunManagedProgram(String, String, String, CompilerOutputParserBase) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:66)
UnityEditorInternal.IL2CPPBuilder:ConvertPlayerDlltoCpp(ICollection`1, String, String) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:425)
UnityEditorInternal.IL2CPPBuilder:Run() (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:275)
UnityEditorInternal.IL2CPPUtils:RunIl2Cpp(String, String, IIl2CppPlatformProvider, Action`1, RuntimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:211)
UnityEditor.HostView:OnGUI()


Exception: /Applications/Unity/Unity.app/Contents/Frameworks/il2cpp/build/il2cpp.exe did not run properly!
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:68)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (ICollection`1 userAssemblies, System.String outputDirectory, System.String workingDirectory) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:425)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:275)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, IIl2CppPlatformProvider platformProvider, System.Action`1 modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:211)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.iOSBuildPostprocessor pp, BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String stagingAreaDataManaged, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (BuildPostProcessArgs args)
UnityEditor.PostprocessBuildPlayer.Postprocess (BuildTarget target, System.String installPath, System.String companyName, System.String productName, Int32 width, Int32 height, System.String downloadWebplayerUrl, System.String manualDownloadWebplayerUrl, BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry) (at /Users/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:316)
UnityEditor.HostView:OnGUI()


Error building Player: Exception: /Applications/Unity/Unity.app/Contents/Frameworks/il2cpp/build/il2cpp.exe did not run properly!
```

**Comment by borrrden** [comment] 2015-06-09 22:51
I didn't realize that IL2CPP was a requirement for making 64-bit apps on iOS.  I guess that will force me to take another look at this, but the distinct lack of guidance about anything regarding IL2CPP has frustrated me.  Things compile fine in Mono, but not IL2CPP with little to no indication about why, and those stack traces lead me to believe it is a problem with IL2CPP, but I'll see if anyone on the Unity forum can point me in the right direction.

**Comment by borrrden** [comment] 2015-06-09 23:56
FYI It seems quite a few people are running into this kind of issue:

http://forum.unity3d.com/threads/ios64-project-with-il2cpp-building-failed.308882/

**Comment by borrrden** [comment] 2015-06-12 23:14
Will try again on the latest patch release when it comes out (5.1.0-p1)

**Comment by heonio** [comment] 2015-06-13 12:26
Do you mean that next version of unity3d (5.1.0-p1) could fix this problem? I will also check it out when it comes out. I am surprised when i see 3 red labels of this issue.

**Comment by borrrden** [comment] 2015-06-13 12:58
According the the forums, yes that might fix it. Otherwise the error is too
vague to track down.

**Comment by zgramana** [comment] 2015-06-14 19:58
@heonio this was also the advice we received from our contact at Unity.

**Comment by borrrden** [comment] 2015-06-19 03:14
Update:  Was able to get rid of the error on this ticket, but ran into another one after that at runtime.  Filed an issue with Unity about it.  Will wait for a response.

**Comment by borrrden** [comment] 2015-07-07 04:48
Update: Unity engineer cannot reproduce, but I sent a reply asking for some clarification on a certain point.  He thinks he can resolve the problem without reproduction, but would like to make sure.  Will look for a fix in the next update.

**Comment by borrrden** [comment] 2015-07-07 21:19
Another update:  Issue confirmed resolved, will be included in the 5.1.2p1 release scheduled for July 22

**Comment by dbergan** [comment] 2015-07-07 21:22
Awesome!

**Comment by BlueHatbRit** [comment] 2015-07-16 17:20
http://unity3d.com/unity/whats-new/unity-5.1.2 was released today. Can we confirm that this issue has been resolved?

**Comment by borrrden** [comment] 2015-07-17 01:35
@BlueHatRit specifically this fix will land in 5.1.2p1, not 5.1.2 according to the support engineer.

**Comment by BlueHatbRit** [comment] 2015-07-17 15:55
@borrrden my bad! Thanks for the clarification. I'll keep an eye out for that case on the patch notes.

Thanks

**Comment by borrrden** [comment] 2015-07-23 05:25
The long awaited patch is finally here, and I can confirm that this particular problem is gone (now I need to start working on the ones that have crept in since)

**Closed** 2015-07-23 05:26 UTC
Labels: blocked, bug, P1: Showstopper, priority-high

**Comment by heonio** [comment] 2015-07-23 18:01
Thank you a lot! :+1:

**Comment by BlueHatbRit** [comment] 2015-07-24 13:58
Just given it a test and it seems to be working, not tested any replications or anything like that but it's all good. Thanks a lot @borrrden :) :+1:
