### ISSUE TITLE
.net app crashes with "System.AccessViolationException"

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#962] opened 2018-02-09 13:41 UTC
I'm running "test_replication_configuration_valid_values" replication test for .net. The app crashes at - https://github.com/couchbaselabs/mobile-testkit/blob/feature/cbl20-ver1/testsuites/CBLTester/CBL_Functional_tests/test_replication.py#L108

Cluster information:

SG -

Build - 2.0.0-773
OS - RHEL7
CBS -

Build - 5.0.0 -3519
OS - RHEL7
.net CBL

Build - 2.0.0-b0520

<img width="1440" alt="screenshot 2018-02-09 19 05 43" src="https://user-images.githubusercontent.com/18100038/36030201-3fbf966a-0dcc-11e8-810e-02d0950ebb2d.png">

Use feature/cbl20-ver1 branch of mobile-testkit repo.
To run the test, follow these steps - 
```
1. update pool.json to below text
{
    "ips": [
    "172.23.109.131",
    "172.23.109.132",
    "172.23.109.133",
    "172.23.109.134"
    ]
}
2. Run  python libraries/utilities/generate_clusters_from_pool.py to generate config files
3. Install CBS server 5.0.0-3519 on 172.23.109.131 ( already installed and configured at this ip). 
    1. Create a bucket name  travel-sample - 
    2. Create an admin user travel-sample with password "password"
4. Install SG 2.0.0-773 on 172.23.109.132 (already installed and configured at this ip)
    1.  Stop SG and update config at /home/syncgateway to below config 
	   {
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,

            "server":"http://172.23.109.131:8091",
            "bucket":"travel-sample",
            "username":"travel-sample",
            "password": "password"
        }
    }
}

       2. Start the SG again
5. Start the .net app from visual studio at 172.23.121.73
6. Run the test using following command - pytest  -rsx -s  --mode=cc --server-version=5.5.0-1812 --sync-gateway-version=2.0.0-773 --liteserv-platform=dotnet --liteserv-host=172.23.121.73  --liteserv-port=55555  --xattrs --skip-provisioning --create-db-per-suite="test_db" --create-db-per-test=pull-test  --no-conflict -k test_replication_configuration_valid_values testsuites/CBLTester/CBL_Functional_tests/test_replication.py
```

**Comment by borrrden** [comment] 2018-02-10 02:06
Are you sure you have pushed your changes to this branch?  The last commit was mine 24 hours ago.

**Comment by hrajput89** [comment] 2018-02-10 08:38
@borrrden, because of merge conflict my changes didn't get pushed. I've pushed them now.

**Comment by borrrden** [comment] 2018-02-10 08:53
The tests keep failing with this error

> E           HTTPError: 409 Client Error: Conflict for url: http://192.168.1.3:4985/db/_user/

I think the test is trying to create a user that already exists.  Have you disabled this when you run?

**Comment by borrrden** [comment] 2018-02-10 09:27
I was able to reproduce this by disabling multiple runs and manually flushing the CBS bucket each time.  It is not in the same place every time and is likely caused by the lack of thread safety around shared keys that was addressed in a recent post-beta commit.  I'll check back again once the .NET builds are stable.

**Comment by borrrden** [comment] 2018-02-13 06:39
NOTE: Blocked by #963 and overall blocked by the build server transition

**Closed** 2018-02-16 07:57 UTC
Labels: P1: high, backlog, functional-test-blocker
