### ISSUE TITLE
ForestDB,1.4-67 net-windows-listener-client-sync-gateway-topology-specific failures

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#810] opened 2017-02-08 21:43 UTC
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway-topology-specific/41/:
 
raise LiteServError("There should be no service running on the port")
E       LiteServError: There should be no service running on the port

**Comment by borrrden** [comment] 2017-02-09 08:59
Duplicate of #815

**Closed by borrrden** 2017-02-09 08:59 UTC
