### ISSUE TITLE
ForestDB,1.2.1-4 net-windows-listener-client-sync-gateway failures

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#812] opened 2017-02-08 21:45 UTC
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway/151/console:

>       client.delete_databases(ls_url)
E           HTTPError: 500 Server Error: Internal error for url: http://172.23.121.129:59840/ls_db

>  raise LiteServError("There should be no service running on the port")
E    LiteServError: There should be no service running on the port

>  raise keywords.exceptions.TimeoutException("Wait for Replication Status Idle: TIMEOUT")
E    TimeoutException: Wait for Replication Status Idle: TIMEOUT

**Comment by borrrden** [comment] 2017-02-14 21:55
Duplicate of #816

**Closed by borrrden** 2017-02-14 21:55 UTC
