### ISSUE TITLE
CB.Lite 2.0.0-db022 Websocket KeyNotFoundException after one-shot replication

### ISSUE THREAD

**Issue by bdgza** [couchbase/couchbase-lite-net#965] opened 2018-02-12 16:13 UTC
Couchbase.Lite 2.0.0-db022 in .NET Standard 2.0 project, part of Xamarin Forms 2.5.0.122203 app, running iOS 11.2 in Simulator, and Windows Forms (.NET 4.7.1) on Windows 10.

I repeatedly perform a one-shot replication to the Gateway 2.0 beta, until the 2nd, or 3rd, or ...th time it crashes the app. On iOS I simply get notification that the sync has stopped, and then within the next second it'll go to black screen/crash without anything in the application output. Once I got the following error logged to output from Lite internals:
```
15:39:45.638630| [Sync] ERROR: (WebSocketTransport) [119] 2018-02-12T15:39:45.6350000+00:00 Websocket Error: System.Exception: Error completing receive for socket ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.4/src/mono/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:223 
  at Couchbase.Lite.Sync.WebSocketTransport.DoCompleteReceive (LiteCore.Interop.C4Socket* socket, System.UInt64 bytecount) [0x00025] in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\src\Couchbase.Lite\Sync\WebSocketTransport.cs:83 
  at LiteCore.Interop.SocketFactory.SocketCompletedReceive (LiteCore.Interop.C4Socket* socket, System.UIntPtr byteCount) [0x00000] in C:\jenkins\workspace\couchbase-lite-net\couchbase-lite-net\vendor\couchbase-lite-core\CSharp\src\LiteCore.Shared\Interop\C4Socket.cs:192 
   --- End of inner exception stack trace ---
```

On Windows desktop repeatedly calling the one-shot replication will throw an exception that triggers my program unhandled exception handler. Log output:
```
2018-02-12 15:57:40.732 +00:00 [Debug] StartSync()
2018-02-12 15:57:40.744 +00:00 [Debug] * REPLICATION START
15:57:40.751138| [BLIP]: {Connection#11}==> class litecore::blip::Connection ->ws:sync.vecmap.com:4984/vecmap/_blipsync
15:57:40.751723| [BLIP]: {Connection#11} Opening connection...
2018-02-12 15:57:40.760 +00:00 [Debug] * REPLICATION STATUS: Connecting
15:57:40.853308| [BLIP]: {Connection#11} Connected!
2018-02-12 15:57:40.878 +00:00 [Debug] * REPLICATION STATUS: Busy
15:57:40.990736| [BLIP]: {Connection#11} Close connection
15:57:41.083080| [BLIP]: {Connection#11} Closed with WebSocket status 1000: 
15:57:41.083838| [BLIP]: {BLIPIO#12}==> class litecore::blip::BLIPIO 000001F77BF5FA48
15:57:41.084458| [BLIP]: {BLIPIO#12} ~BLIPIO: Sent 139 bytes, rcvd 109. Max outbox depth was 1, avg 1.00
15:57:41.087118| [Sync] ERROR: (WebSocketTransport) [73] 2018-02-12T15:57:41.0866220+00:00 Websocket Error: System.Exception: Error completing receive for socket ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Couchbase.Lite.Sync.WebSocketTransport.DoCompleteReceive(C4Socket* socket, UInt64 bytecount)
   at LiteCore.Interop.SocketFactory.SocketCompletedReceive(C4Socket* socket, UIntPtr byteCount)
   --- End of inner exception stack trace ---
15:57:41.096078| [WS] WARNING: {Logging#13}==> class litecore::Logging 000001F778FEC658
15:57:41.096549| [WS] WARNING: {Logging#13} Unexpected or unclean socket disconnect! (reason=Unknown error, code=17)
2018-02-12 15:57:41.096 +00:00 [Debug] * REPLICATION STATUS: Stopped
2018-02-12 15:57:41.102 +00:00 [Debug] * REPLICATION STOPPED/OFFLINE, Moving on
```

Since both trigger a `System.Collections.Generic.KeyNotFoundException` I am assuming these errors are related, and I am hoping that this is also the cause of the iOS app hard crashing.

There is nothing regarding this reported in the Gateway log.

**Comment by borrrden** [comment] 2018-02-12 21:24
Duplicate of #963

**Closed by borrrden** 2018-02-12 21:24 UTC
Labels: P1: high

**Comment by borrrden** [comment] 2018-02-12 21:57
This issue was caught too late for db022, but a remedy has been made.  This shouldn't happen unless a replication actually stops (which one shot does).  If you use continuous for now you should be able to work around.

**Comment by borrrden** [comment] 2018-02-12 21:58
Also yes, these are the same on both.  There is a race which affects whether or not the app will just have an unhandled exception or will go down with a native crash (or not have anything go wrong at all)
