### ISSUE TITLE
Native memory leak when inserting repeatedly

### ISSUE THREAD

**Issue by benharden** [couchbase/couchbase-lite-net#1196] opened 2019-12-10 15:24 UTC
CouchbaseLite/2.6.0 (.NET; UWP 10.0.18363.476; Dell Inc. XPS 15 9570) Build/129 LiteCore/2.6.0 (2193) Commit/e715812a

### Library Version
2.6.0 (2193) 

### .NET Runtime
UWP 10.0.18363.476

### Operating System / Device Details
Windows 10 Enterprise

### Expected behavior
The reproduction project should run indefinitely without running out of memory.

### Actual behavior
The native heap size climbs rapidly as the reproduction project continues to insert records. This can be seen when running the project in Visual Studio 2019 and observing the diagnostic tools.

### Steps To Reproduce
Run the supplied reproduction project. The reproduction project does the following:
```csharp
var directoryPath = Path.GetTempPath();

while (true)
{
	// asynchronously insert a record into the database
	await Task.Run(() =>
	{
		var timestamp = DateTime.UtcNow;

		// create the record to be stored
		var record = new Dictionary<string, object>()
		{
			{ "Timestamp", timestamp.Ticks },
			{ "Value", "test" }
		};

		var config = new DatabaseConfiguration()
		{
			Directory = Path.Combine(directoryPath)
		};

		// create the database
		using (var db = new Database(name: "MyDatabase", config))
		{
			// convert the record to a mutable document and save it
			using (var document = new MutableDocument(timestamp.Ticks.ToString(), record))
			{
				db.Save(document);
			}
		}
	}).ConfigureAwait(false);

	// wait briefly before inserting another record
	await Task.Delay(10).ConfigureAwait(false);
}
```

### Reproduction Project
[CouchbaseMemoryLeak.zip](https://github.com/couchbase/couchbase-lite-net/files/3945572/CouchbaseMemoryLeak.zip)

**Comment by Sandychuang8** [comment] 2019-12-10 20:01
Hi there, If you want to test memory profiling on continuous adding documents into the database, it's better to move creating DatabaseConfiguration and Database out of the BeginInsertsAsync method.

**Comment by Sandychuang8** [comment] 2019-12-11 01:26
FYI: in the reproduction project you provided, index is only needed to be created once in the app life cycle. The 2nd + time on index creation will be no-op.

**Comment by Sandychuang8** [comment] 2019-12-11 02:22
Thanks for reporting. We found a leak and filed a ticket [580](https://issues.couchbase.com/browse/CBL-580)

**Comment by borrrden** [comment] 2019-12-11 02:34
To add some more info, you will only see this leak by repeatedly opening and closing the database and saving documents as you do.  If you do not open the database in a loop you will not see the issue.

**Comment by benharden** [comment] 2019-12-20 15:04
Many thanks for your work on this.

I tested the [580](https://issues.couchbase.com/browse/CBL-580) change and in the test program memory usage is much better.  But shows one final native leak in this stack trace:

![image](https://user-images.githubusercontent.com/13018890/71263542-f9d7d100-2339-11ea-8e12-98541c117e5a.png)
![image](https://user-images.githubusercontent.com/13018890/71263551-fd6b5800-2339-11ea-860a-77869682d9d1.png)
![image](https://user-images.githubusercontent.com/13018890/71263557-ffcdb200-2339-11ea-8a88-47005949d141.png)
![image](https://user-images.githubusercontent.com/13018890/71263570-078d5680-233a-11ea-9794-617f4c510573.png)
![image](https://user-images.githubusercontent.com/13018890/71263575-0a884700-233a-11ea-97f1-e260e7cc9a90.png)

**Comment by borrrden** [comment] 2019-12-20 22:30
I don't see how that is our leak.  It doesn't pass through any unmanaged code owned by us.

**Comment by pilcherd** [comment] 2019-12-21 16:26
> I don't see how that is our leak. It doesn't pass through any unmanaged code owned by us.

I'm on Ben's team and we have reported that to Microsoft as it looks like this leak is in their library.

What is the release schedule for Couchbase-lite for getting a version with the memory leak reported in nuget?  

Many thanks

**Comment by borrrden** [comment] 2020-01-01 01:34
I don't have the authority to say the exact schedule but it will be in 2.7.1, the release after next (the next release *should be* coming this month, the release after is not scheduled concretely yet but in the window of another month or two).

**Comment by stickybun** [comment] 2020-01-07 10:26
Is there a way we can access this fix before 2.7.1 is released?

From the documentation:

> There will be developer builds compiled every two weeks, and available by adding http://mobile.nuget.couchbase.com/nuget/Developer/ to your Nuget package sources.

However,  the server appears to be down. 

Can this be made available?

**Comment by borrrden** [comment] 2020-01-07 10:31
Sorry about that documentation.  We haven't been doing biweekly builds in quite some time because our release cadence is always busy.  You can certainly build from source if you are in a hurry.  @Sandychuang8 should be able to point you to a commit that fixed this.  In the meantime, the workaround should prevent the memory buildup.

**Comment by terryban** [comment] 2020-01-10 15:56
I am also a colleague of Ben and I am trying to build Couchbase-lite from the source. I am finding it quite a struggle. Do you have some advice on the best way to do it? I am using VisualStudio 2017 and I need a build for UWP on a x64 platform. Thanks.

**Comment by Sandychuang8** [comment] 2020-01-10 22:16
Hi there,
You first will need to build LiteCore first https://github.com/couchbase/couchbase-lite-core#windows-desktop then you can follow the instruction in https://github.com/couchbase/couchbase-lite-net

**Comment by NgyAnthony** [comment] 2020-07-09 12:30
Issue fixed [CBL-580](https://issues.couchbase.com/browse/CBL-580)

**Comment by Sandychuang8** [comment] 2021-01-06 23:20
The issue is fixed in the later release.

**Closed by Sandychuang8** 2021-01-06 23:20 UTC
Labels: bug, triaged
