### ISSUE TITLE
UWP: Can not create database

### ISSUE THREAD

**Issue by mohsens22** [couchbase/couchbase-lite-net#857] opened 2017-05-11 22:29 UTC
Hello.
UWP DP5 is a real bug : D 
I couldn't make database .

`
  public static void CreateDB()
        {
            Couchbase.Lite.Support.UWP.Activate();
            var database = DatabaseFactory.Create("Xugros");
}
`
I get the error : 
![image](https://cloud.githubusercontent.com/assets/22152065/25974558/fffc97ec-36be-11e7-9113-83d550c9e56d.png)
![image](https://cloud.githubusercontent.com/assets/22152065/25974568/0e60d64a-36bf-11e7-83f0-17ffcfa55825.png)

**Comment by borrrden** [comment] 2017-05-12 10:38
This looks like missing native DLLs. Can you confirm that they are present (LiteCore.dll and SQLite3.dll inside the appx directory inside of an x64 folder). Also just in case I need to ask is this ARM?  ARM won't work.

**Comment by mohsens22** [comment] 2017-05-12 11:16
@borrrden So I'll add another issue: "Couchbase.Lite does not work on ARM, WHY?!??" LOL.
I had problem with SQLite PCL before on ARM and it had to be a Release package to work fine in ARM.
The configuration was X86 Debug. I cleaned the project and recompiled in X64 Release. Again BUG :(
![image](https://cloud.githubusercontent.com/assets/22152065/25995801/5824e0fe-3729-11e7-89a0-8ffdc2641047.png)
SQLite3.dll is present. LiteCore.dll is present too. (x64-release.)
LiteCore.dll is present. SQLite3.dll is present too.(x86-debug.)

**Comment by borrrden** [comment] 2017-05-12 12:48
I should clarify that it just doesn't work on WINDOWS ARM.  The reason is because there hasn't been any demand for it so far and so I haven't put effort into it.  

That second exception is something I've never seen before.  This problem may not exist anymore even, because DB5 is based on one month old source.  DB7's source will be ready soon and it has a huge API refactor.  I hate that we can't release it because some of the other platforms are having trouble getting releases onto the web for other reasons...but that's the way things are right now.  If you are feeling adventurous you could try compiling the library yourself too ;).  I've seen the first exception before when compiling the library myself and linking the project but never with the actual nupkg....

**Comment by mohsens22** [comment] 2017-05-12 13:34
@borrrden 
Anyway, I can not make any database. Please fix it and publish the nupkg ASAP.  If you want I can get you git access to the project inorder to see the error in action.

**Comment by mohsens22** [comment] 2017-05-12 13:42
@borrrden 
And look at #858 and clarify that why didn't you do ARM stuff. And when will you implement that.

**Comment by borrrden** [comment] 2017-05-16 02:11
This second exception finally happened for me, and it has to do with .NET Native.  It seems that disallowed API is causing this thing to blow up.  There were a few details that I didn't get from the screen shot (like which API is causing this) so now I can start to move in on those.  DB7 is already finalized though so it won't be in that.  It should work without .NET Native compilation enabled though.

**Comment by borrrden** [comment] 2017-05-16 03:30
This was maddening to try to figure out and I wish there were some information about the requirements of this from Microsoft....I got it to work with .NET Native now.  There were two main things wrong with the current approach:

1. P/Invoke into disallowed `LoadLibraryEx` (needs to be `LoadPackagedLibrary` instead)
2. The native DLLs have to be in the same directory as the managed ones, meaning that putting them in x86, x64 subfolder will result in them not being found.  Furthermore, `LoadPackagedLibrary` will not accept a path as its input like `LoadLibraryEx` does.  

Since UWP requires compilation per platform it is not as much of an issue to put the native DLLs there though.  The reason they are in folders like that is because of .NET Core, which doesn't require to know its architecture ahead of time and so both x86 and x64 must be available and it cleverly chooses at runtime.  I will begin the process of splitting the library completely into a managed package (Couchbase.Lite) and native packages per platform (Couchbase.Lite.Support.*) for every platform we support.  That will create the easiest way to keep all these native binaries isolated from each other.  This is also what I mentioned in the ARM ticket.

**Comment by borrrden** [comment] 2017-05-18 05:34
I confirmed the unit tests now pass with .NET Native enabled.  That fix will go into DB8.  DB7 will be released soon (I ask my manager every day if I can release it but I have to wait for other managerial things first...)

**Comment by borrrden** [comment] 2017-05-19 23:37
Ok I finally got the go-ahead to push DB7 -_-.  Make sure you try it without .NET Native on a non-ARM device.

**Comment by mohsens22** [comment] 2017-05-19 23:46
@borrrden  TADA !!!!
Finally :D

**Comment by mohsens22** [comment] 2017-05-19 23:46
@borrrden  Send me some docs about DB7 if it's ready :)

**Comment by mohsens22** [comment] 2017-05-19 23:55
![image](https://cloud.githubusercontent.com/assets/22152065/26270876/2640d750-3d14-11e7-9fb7-5b8832ad973b.png)
@borrrden  Congratulation guys. you did a very big improvement. I get a straight syntax error while making a database rather than a runtime error. Thank you !!! :(

**Comment by borrrden** [comment] 2017-05-19 23:58
The API has changed :).  See the [GH Release](https://github.com/couchbase/couchbase-lite-net/releases/tag/2.0.0-db007) for more details.  Now you should create a database class instance directly instead of using a factory (The factories were getting out of control).  

Also be warned that encryption is not yet implemented so don't try to use it or you will get an exception saying it is not implemented.

**Comment by mohsens22** [comment] 2017-05-20 00:01
@borrrden  Fastest API change EVER :| 
I can bet before public release we would have a millions of them ...
Anyway, Thank you :) Gonna test it soon (TM)

**Comment by borrrden** [comment] 2017-05-20 00:05
Yes, this is the only time I can mess around with the public API so expect changes.  I hope this is the last big one but I can't be 100% sure.  Heads up that DatabaseOptions will change to DatabaseConfiguration in DB8, and the Replication API is not finalized.

**Comment by mohsens22** [comment] 2017-05-20 00:07
Cool, But I'm a bit confused with this build. I see just an API for making a database. I see really nothing for getting one !!!

**Comment by borrrden** [comment] 2017-05-20 00:25
Creating and getting are the same thing now.  If it exists, then that is what you get.

**Comment by mohsens22** [comment] 2017-05-20 01:06
![image](https://cloud.githubusercontent.com/assets/22152065/26271664/16783d9a-3d1e-11e7-9f6f-0d9db94e5d2a.png)
 Cool.
If you ask me about "Turning off the .NET native"  I would tell you I didn't because I donno how to do it.

**Comment by borrrden** [comment] 2017-05-20 01:12
By default it is off in Debug mode, but it is on the [project properties page](https://msdn.microsoft.com/en-us/library/dn600164(v=vs.110).aspx#Anchor_1) so you can disable it in release mode as well.  If it still doesn't work then I'm not sure what to do next because I have confirmed that it works in a UWP unit test app.

**Comment by mohsens22** [comment] 2017-05-20 01:15
@borrrden  Checked. No .NET native compile. So WHAT TO DO next?

**Comment by borrrden** [comment] 2017-05-20 02:56
Tell me some information about your project environment.  I run the unit test app on an x64 Windows 10 machine and I don't see the problem.  Alternatively, try to run the unit test runner in your environment and see if it fails in the same way.

**Comment by mohsens22** [comment] 2017-05-20 13:47
I tested that app in debug_X64 UWP again bug :|

**Comment by borrrden** [comment] 2017-05-20 13:54
One thing I just thought of that I might have overlooked. Do you have visual studio 2015 installed and/or the visual studio 2015 c++ runtime?  Missing that is another reason for LiteCore not being able to be loaded (adding the 2015 c++ windows extension to your project might also do the trick but I'm not sure about that)

**Comment by mohsens22** [comment] 2017-05-20 13:57
I run VS17 with full components installed. And included  2015 c++ windows extension. Again bug .

**Comment by mohsens22** [comment] 2017-05-20 13:58
I'm gonna test CB.Lite in Win32 and other UWP projects and trying to build unit test too find out more about this bug

**Comment by borrrden** [comment] 2017-05-20 14:00
Installing [this](https://www.microsoft.com/en-us/download/details.aspx?id=53587) might help. This is the c++ runtime that comes with visual studio 2015 which is what LiteCore is compiled with. If this is a dependency then I will need to figure out how to package it along with Nuget.

**Comment by mohsens22** [comment] 2017-05-20 14:11
![image](https://cloud.githubusercontent.com/assets/22152065/26276390/f39424ce-3d8b-11e7-9cd6-5cc1fbe051db.png)
Seems that I have it :)

**Comment by mohsens22** [comment] 2017-05-20 20:27
![image](https://cloud.githubusercontent.com/assets/22152065/26279131/73a21d18-3dc0-11e7-83de-1a4973968041.png)
While trying to build Unit tests

**Comment by mohsens22** [comment] 2017-05-20 20:41
Tested on WPF : Works just fine.
on UWP still that error ....

**Comment by borrrden** [comment] 2017-05-20 22:46
What is the error message when trying to load the Couchbase.Lite.Tests.UWP project (Maybe it's that it is using a different version of the UWP tools than you have)?  As for git, that looks like a [git issue](https://stackoverflow.com/questions/7605469/git-submodules-pulling-into-a-new-clone-of-the-super-project).  That being said, for the unit tests you shouldn't need the submodule.  All of the test source is contained in the root project.  If you can get it to load, then build the unit test app with the "Packaging" configuration (instead of Debug or Release, which will likely throw an error because I had to hack around UWP not copying subproject native DLLs)

**Comment by mohsens22** [comment] 2017-05-20 22:58
I fixed the git issue and got the sub module. And errors gone. What project to build?

**Comment by borrrden** [comment] 2017-05-20 23:06
Firstly, the unit test package (Couchbase.Lite.Tests.UWP) is pointing to internal CI packages so it won't be able to download them.  Fix them to point to DB7.  Then make sure .NET Native compilation is disabled on the Packaging configuration.

After that, you should be able to build the Packaging configuration.  I test with Packaging|x64 on the build server.  After it is build you should open the Unit Test Explorer in Visual Studio and see the various unit tests.  Try running any of them.  If the same problem is present over there then the vast majority should throw the exception you are seeing.

That being said, working on WPF and not on UWP is a bit odd because they both use the exact same native binaries in DB7.  Part of the fix that is going into DB8 is that I am moving the LiteCore.dll and sqlite3.dll files from the x64 (or x86, whatever) folder up one level to be next to Couchbase.Lite.dll.  I really hope that it doesn't have to do with the version of Windows 10 being used.   The build server is running Windows 10.0.14393 and my desktop is running Windows 10.0.15063.

**Comment by mohsens22** [comment] 2017-05-20 23:19
I'm running 10.0.15063 with all UWP SDKs.
![image](https://cloud.githubusercontent.com/assets/22152065/26279938/56df4fe4-3dd8-11e7-8a84-2732ea0ed7af.png)

5 mins passed and I really see no output from unit tests (It's still running)

**Comment by borrrden** [comment] 2017-05-20 23:22
You need to use the [Test Explorer](https://msdn.microsoft.com/en-us/library/hh270865.aspx) in Visual Studio to run tests.  Running the project directly just starts an app which does nothing (that UI is the default for the test runner, which is misleading).

**Comment by mohsens22** [comment] 2017-05-20 23:23
I'll try, But I think xUnit I not like that...

**Comment by borrrden** [comment] 2017-05-20 23:24
UWP does not use xUnit.  It uses MSTest because I couldn't get xUnit to work reliably for UWP.

**Comment by mohsens22** [comment] 2017-05-20 23:29
Test scores are awesome:
![image](https://cloud.githubusercontent.com/assets/22152065/26279966/9febd396-3dd9-11e7-8bd2-58bb73f85695.png)

But the tricky thing is that, When I clicked (Run all) It went into an issue and said (Do you wanna run last successful build?) I clicked OK, The tests ran and the app force closed.

**Comment by borrrden** [comment] 2017-05-20 23:53
I just reconfirmed that all of the unit tests pass here for me with DB7, so I think you can see the conundrum now...

![testresults](https://cloud.githubusercontent.com/assets/2470288/26280093/40383f24-3e02-11e7-81a7-cb7ae425d446.png)

There is a tool I sometimes use called [Dependency Walker](http://www.dependencywalker.com/) that will show the native deps of a given exe or dll.  Here is what it looks like for LiteCore:

![depwalker](https://cloud.githubusercontent.com/assets/2470288/26280095/666fa92a-3e02-11e7-8a42-0ec739cce22e.png)

SQLite does not have any dependencies that do not show up in the above picture.  If you run the tool I mentioned and open LiteCore do you notice any yellow circles that are not present in the above picture?  I shouldn't think so because of the fact that it works with WPF...

Just to be clear, are you running these tests on the same machine (WPF vs UWP?).  If you are deploying to another device, then things would make more sense and the C++ package I mentioned needs to be installed on the *deployment* device.  And can you paste the full errors that you receive (The InnerException as well) or indicate that they are one of the ones you already posted?

**Comment by mohsens22** [comment] 2017-05-21 00:12
They really look alike.
![image](https://cloud.githubusercontent.com/assets/22152065/26280229/a9a34eea-3ddf-11e7-8c8a-65be8bf1ef8b.png)
I run the same tests on same machine with same code in UWP and WPF. And I told you, I downloaded the C++ pack and it told me you had a greater version installed.
I'm gonna send you errors in detail ...

**Comment by mohsens22** [comment] 2017-05-21 00:24
System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Couchbase.Lite.Database' threw an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Couchbase.Lite.Database..ctor(String name, DatabaseOptions options)
   at Core.Models.DBH.CreateDB() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 22
   at Core.Models.DBH.MakeDoc(Dictionary`2 Dic) in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\DBH.cs:line 31
   at Core.Models.UserModel.<CreateUser>d__0.MoveNext() in C:\Users\Mohsen\Source\Repos\Denna\Denna\Core\Models\UserModel.cs:line 38

Inner Exception 1:
TypeInitializationException: The type initializer for 'LiteCore.Interop.Native' threw an exception.

Inner Exception 2:
LiteCoreException: LiteCoreException (17): unexpected exception

**Comment by mohsens22** [comment] 2017-05-21 00:29
![image](https://cloud.githubusercontent.com/assets/22152065/26280297/3cc278de-3de2-11e7-8436-81fb7f2d8450.png)
and my C++ packages

**Comment by borrrden** [comment] 2017-05-21 00:58
Ok so that seems to be the same as above which means either LiteCore.dll could not be *found* or it could not be *loaded* (if you run inside of a debugger, you should see output in the debug that says either 'Could not find LiteCore.dll!  Nothing is going to work!' or 'Could not load LiteCore.dll!  Nothing is going to work!').  I actually changed the exception thrown after DB7 so that it would be more easy to tell apart, but the former means that no file was found to load, and the latter means there was a problem loading it.  [This](https://github.com/couchbase/couchbase-lite-core/blob/ab7f9710c1b1cbdfad6a3c5edbb9dfa9f21fb2e6/CSharp/src/LiteCore.Shared/Interop/C4Base.cs#L270) is the logic for loading the DLL (this is going to change for UWP in DB8 due to what I mentioned in the ticket about ARM).  

I have a build of the new version that I mentioned above.  I will attach it to this ticket.  It uses the simplified way of loading the DLL (which is just to copy the architecture in question to the root).  It also passed all the unit tests (although that does not appear to mean much...).  Note that if you try this one with WPF, you will need to call `NetDesktop.Support.Activate()`.  To post them here I had to add a zip extension, so remove the zip extension instead of unzipping it.  Maybe you can finally get a break with it.

[Couchbase.Lite.2.0.0-b0082.nupkg.zip](https://github.com/couchbase/couchbase-lite-net/files/1016584/Couchbase.Lite.2.0.0-b0082.nupkg.zip)
[Couchbase.Lite.Support.NetDesktop.2.0.0-b0082.nupkg.zip](https://github.com/couchbase/couchbase-lite-net/files/1016586/Couchbase.Lite.Support.NetDesktop.2.0.0-b0082.nupkg.zip)
[Couchbase.Lite.Support.UWP.2.0.0-b0082.nupkg.zip](https://github.com/couchbase/couchbase-lite-net/files/1016585/Couchbase.Lite.Support.UWP.2.0.0-b0082.nupkg.zip)

**Comment by mohsens22** [comment] 2017-05-21 01:24
Good job sir ! Seems fine.
![image](https://cloud.githubusercontent.com/assets/22152065/26280449/c1d5e072-3de9-11e7-83e5-a197a56bc29b.png)
I'll fully test it in my project these days :D

**Comment by borrrden** [comment] 2017-05-21 01:30
Phew.  DB8+ is going to have this style of loading so hopefully this will be forever behind us.  On a side note, this build includes ARM support (more details on the other ticket).

**Closed by borrrden** 2017-05-21 01:30 UTC
Labels: ready
