### ISSUE TITLE
Replication stuck in busy state with test_multiple_cbls_updates_concurrently_with_push

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#980] opened 2018-02-27 22:23 UTC
### Builds
.net 2.0.0-b0571, SG 2.0.0-812, CBS 5.5.0-1924

### Test Ran
```
pytest -s --mode=di --server-version=5.5.0-1924 --sync-gateway-version=2.0.0-812 --liteserv-platform=net-msft --liteserv-host=192.168.33.21 --liteserv-port=55555  --xattrs testsuites/CBLTester/CBL_Functional_tests/test_no_conflicts_cbl.py --liteserv-version=2.0.0-b0571 -k test_multiple_cbls_updates_concurrently_with_push  --create-db-per-test test-db --skip-provisioning
```
### Actual
The test times out waiting for replicator to go idle.
Test output
```
....
Activity level: busy
Got response: 
Got response: "busy"
Activity level: busy
FAILED
.....
>       replicator2.wait_until_replicator_idle(repl)
.....
E           Failed: Timeout >900s
```

### CBL logs
```
INFO) Sync {DBWorker#10} Saved local checkpoint cp-42vjx9lioMn1AspGRraDwa9UphU= to db
INFO) Sync (Replicator) [13] 2018-02-27T13:53:37.7792737-08:00 Replicator[<*> DB[C:\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer.NetCore\bin\Debug\netcoreapp2.0\CouchbaseLite\cbl_db21519768338.06.cblite2\]] is Busy, progress 840570/859654
INFO) Sync (Replicator) [12] 2018-02-27T13:53:37.7870335-08:00 Replicator[<*> DB[C:\mobile-testkit\CBLClient\Apps\CBLTestServer-Dotnet\TestServer.NetCore\bin\Debug\netcoreapp2.0\CouchbaseLite\cbl_db21519768338.06.cblite2\]] is Busy, progress 840570/859654
```
The replicator is stuck in busy state and there is no activity.

**Comment by raghusarangapani** [comment] 2018-02-27 22:28
The test has 3 parametrized cases
```
@pytest.mark.parametrize("sg_conf_name, num_of_docs, number_of_updates", [
    ('listener_tests/listener_tests_no_conflicts', 10, 2),
    ('listener_tests/listener_tests_no_conflicts', 100, 10),
    ('listener_tests/listener_tests_no_conflicts', 100, 50)
])
def test_multiple_cbls_updates_concurrently_with_push(params_from_base_test_setup, setup_customized_teardown_test, sg_conf_name, num_of_docs, number_of_updates):
```
The first one with 10, 2 always passes. The other two always timeout as the number_of_updates is more.

**Comment by borrrden** [comment] 2018-02-28 08:06
I have tried to debug this but nothing is going wrong inside the .NET side...and I haven't been able to decipher what is happening on the native side.  @snej Can you give me some debugging hints?  I can put breakpoints anywhere in either native or managed code (but not both at the same time).  There are no exceptions thrown in either LiteCore or Couchbase Lite (except for a ton of fleece exceptions that mark the end of a dictionary iterator that then get caught and swallowed).  The logs are a hot mess of errors about 409 from pushing to other DBs, and "fake" pull conflicts (which somehow get marked as conflicts even though there are none).  I imagine this would reproduce on other platforms!

**Comment by snej** [comment] 2018-02-28 17:31
The stuck-busy state is usually caused by one of the Workers (Replicator, Pusher, Puller, etc.) getting mixed up in its count of things left to do. This is determined in the `computeActivityLevel()` method. These methods have Debug-level log messages that dump the values that are used to compute the activity level. To debug this I usually set the log level to Debug (in a debug build) and look at these messages in backwards order in the log, looking for one that still ends up Busy.

**Comment by borrrden** [comment] 2018-03-02 23:16
Does this still happen in 601 @raghusarangapani  ?

**Comment by raghusarangapani** [comment] 2018-03-03 00:48
Issue still reproducible with .net b0601

**Comment by snej** [comment] 2018-03-03 01:27
I just wrote a [wiki doc](https://github.com/couchbase/couchbase-lite-core/wiki/Debugging-Replicators-Stuck-In-Busy) on how to debug these kinds of bugs.

**Comment by borrrden** [comment] 2018-03-03 02:59
The wiki doc is helpful in determining *what* is holding up a replication, but the reason is still unclear.  I have taken a run of the logs while an app was stuck and divided them into four parts.  There are two replications going on:  Continuous push-pull from CBL1 to CBL2, and Continuous push-pull from CBL1 to CBL3 and so the parts are as follows:

[cbl2_passive.txt](https://github.com/couchbase/couchbase-lite-net/files/1777036/cbl2_passive.txt) - Logs regarding the "passive" replication on CBL2.  This replication is stuck due to what looks like something causing the changes list processing to stop in the pusher.  The number of entries keeps growing and the pusher stays busy.

[cbl1_2_continuous.txt](https://github.com/couchbase/couchbase-lite-net/files/1777041/cbl1_2_continuous.txt) - The other "active" side of the same replication.  It claims to be busy for both push and pull.  The pull is waiting for pending rev messages and the push is waiting for changes lists.

[cbl3_passive.txt](https://github.com/couchbase/couchbase-lite-net/files/1777043/cbl3_passive.txt) - The passive replication for CBL3.  The pusher and pull are both busy.  The pusher has a whole lot of things that it is waiting for (changeList, revsToSend, and pendingSequences).  The puller has pending rev messages.

[cbl1_3_continuous.txt](https://github.com/couchbase/couchbase-lite-net/files/1777044/cbl1_3_continuous.txt) - The other side of the CBL3 replication.  Puller and Pusher both busy.  Pusher has changesLists waiting, and puller has pending rev messages.

Does this look like the flow of data simply stopped?

**Comment by snej** [comment] 2018-03-05 20:11
Thanks a lot for capturing all this. Let me see...

* cbl2_passive -- `changeLists=229` means it's waiting for replies to 229 `proposeChanges` messages it's sent to the peer.
* cbl1_2_continuous -- It's stalled out for a long time with `_pendingRevMessages=46`, meaning it's waiting for 46 `rev` messages from the peer.
* Sure enough, `cbl2` has `revsToSend=46`. So why isn't it sending `rev` messages? That's triggered by `Pusher::maybeSendMoreRevs()` ... which implies that method isn't being called.
* I think the culprit is `_couldntSendRevision()`, which is a new method called when a `rev` message can't be sent because the revision's been overwritten. It calls `doneWithRev()`, but not `maybeSendMoreRevs()` -- I'll add that call to it.

**Comment by snej** [comment] 2018-03-05 20:16
This issue was moved to couchbase/couchbase-lite-core#446

**Closed by snej** 2018-03-05 20:16 UTC
Labels: P1: high, ready
