### ISSUE TITLE
CBL exception messages are not consistent with android and iOS

### ISSUE THREAD

**Issue by hrajput89** [couchbase/couchbase-lite-net#958] opened 2018-02-07 11:58 UTC
The exception messages coming from .net are not consistent with Android and iOS API.

For example - 
This is the exception msg we get when getDocument method is called with null value.

- .net

> 03:55:17.791582| [DB] ERROR: (Database) [3] 2018-02-07T03:55:17.7915348-08:00 System.ArgumentNullException: Value cannot be null.
> Parameter name: id
> Error in handler for http://172.23.121.73:55555/database_getDocument: **Value cannot be null.**
> Parameter name: id

Android

> I/System.out: java.lang.reflect.InvocationTargetException
> I/System.out:     at java.lang.reflect.Method.invoke(Native Method)
> I/System.out:     at com.couchbase.CouchbaseLiteServ.server.Server.handle(Server.java:178)
> I/System.out:     at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:421)
> I/System.out:     at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
> I/System.out:     at java.lang.Thread.run(Thread.java:761)
> I/System.out: Caused by: java.lang.IllegalArgumentException: **a documentID parameter is null**
> I/System.out:     at com.couchbase.lite.Database.getDocument(Database.java:224)
> I/System.out:     at com.couchbase.CouchbaseLiteServ.server.RequestHandler.DatabaseRequestHandler.getDocument(DatabaseRequestHandler.java:91)
> I/System.out: 	... 5 more

**Comment by snej** [comment] 2018-02-07 16:51
* Passing illegal values to a method is undefined behavior, and that will produce undefined results, i.e. there is no guarantee what will happen.
* Our API has no specification for errors/exceptions. It has never been stated that the errors or their messages will be the same on all platforms.

**Comment by borrrden** [comment] 2018-02-19 01:45
Duplicate of #956

**Closed by borrrden** 2018-02-19 01:45 UTC
Labels: P1: high, backlog
