### ISSUE TITLE
ForestDB,1.4-67  net-windows-listener-client-sync-gateway failures

### ISSUE THREAD

**Issue by raghusarangapani** [couchbase/couchbase-lite-net#809] opened 2017-02-08 21:41 UTC
http://uberjenkins.sc.couchbase.com:8080/job/net-windows-listener-client-sync-gateway/158/console:
 
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[True] 
      SETUP    F setup_client_syncgateway_test (fixtures used: setup_client_syncgateway_suite)
      SETUP    F continuous[True]
        testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[True] (fixtures used: continuous, environment, setup_client_syncgateway_suite, setup_client_syncgateway_test)FAILED
      TEARDOWN F continuous[True]
      TEARDOWN F setup_client_syncgateway_test
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[True] ERROR
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[False] 
      SETUP    F setup_client_syncgateway_test (fixtures used: setup_client_syncgateway_suite)
      SETUP    F continuous[False]
        testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[False] (fixtures used: continuous, environment, setup_client_syncgateway_suite, setup_client_syncgateway_test)FAILED
      TEARDOWN F continuous[False]
      TEARDOWN F setup_client_syncgateway_test
testsuites/listener/shared/client_sg/test_replication.py::test_initial_push_replication[False] ERROR
testsuites/listener/shared/client_sg/test_replication.py::test_multiple_replications_not_created_with_same_properties 
      SETUP    F setup_client_syncgateway_test (fixtures used: setup_client_syncgateway_suite)
 
testsuites/listener/shared/client_sg/test_replication.py::test_replication_with_session_cookie 
      SETUP    F setup_client_syncgateway_test (fixtures used: setup_client_syncgateway_suite)
        testsuites/listener/shared/client_sg/test_replication.py::test_replication_with_session_cookie (fixtures used: environment, setup_client_syncgateway_suite, setup_client_syncgateway_test)Build timed out (after 45 minutes). Marking the build as failed.

**Comment by borrrden** [comment] 2017-02-14 21:55
Duplicate of #816

**Closed by borrrden** 2017-02-14 21:55 UTC
