### ISSUE TITLE
Random write behaviour when PushReplication set to continuous. (Couchdb or Couchbase)

### ISSUE THREAD

**Issue by sherry-ummen** [couchbase/couchbase-lite-net#258] opened 2014-09-01 03:14 UTC
What I do is set the PushReplication to continous before the write starts to happen so that whatever I write local data store it should instantly be replicated to remote server which in my case is couchdb.

But when I do I see the random behaviour where the datra is written in to the local data store but it does not get replicated and sometime it happens so that only partial gets replicated.

One more behaviour is seen that if the continous replication is on and due to this random failure of replication the write to local store also hangs.

**Comment by zgramana** [comment] 2015-01-19 20:20
Duplicate of couchbase/couchbase-lite-net#319.

**Closed by zgramana** 2015-01-19 20:20 UTC
Labels: duplicate
