### ISSUE TITLE
[db023/SQLite error]- Replication errors for bucket with 200000+

### ISSUE THREAD

**Issue by thomas1983** [couchbase/couchbase-lite-net#996] opened 2018-03-16 10:56 UTC
CBL: db023
SGW: 2.0 Beta2
CB: 5.5

Prob: Replication errors (SqLite) for bucket with 200000+, cannot open file at line xxxx
Situation: Sequential non-continuous push and pull replication of 9 buckets
Remarks: smaller buckets (1000-) seem to run fine. See attached file for detailed output

```
00:45:01
.036068| WARNING: SQLite error (code 14): 
cannot open file at line 36229 of [1a584e4999]
00:45:01.037571| WARNING: SQLite error (code 
14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 

00:45:04
.825769| WARNING: 
SQLite error (code 14): 
cannot open file at line 36229 of [1a584e4999]
00:45:04
.830157| 
WARNING: 
SQLite error (code 
14
): 
os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
Thread finished:  #6390
Thread finished:  #6392
Thread finished:  #6391
00:45:05
.872359| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.872869| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05.880681| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.881024| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05.884022| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.884356| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05.887380| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.887712| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05.890891| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.891212| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05.894602| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.894952| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
00:45:05
.898199| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.898591| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 03-16 11:08:35.890 W/Adreno-EGLSUB(15994): <DequeueBuffer:700>: dequeue native buffer fail: Unknown error 2147483646, buffer=0x0, handle=0x0

03-16 11:08:35.890 W/Adreno-EGLSUB(15994): <DequeueBuffer:700>: dequeue native buffer fail: Invalid argument, buffer=0x0, handle=0x0
03-16 11:08:35.890 W/Adreno-EGL(15994): <qeglDrvAPI_eglSwapBuffers:3730>: EGL_BAD_SURFACE
00:45:05.902891| WARNING: SQLite error (code 14): cannot open file at line 36229 of [1a584e4999]
00:45:05.903228| WARNING: SQLite error (code 14): os_unix.c:36229: (24) open(/data/data/com.Xxxxx.XxxxxXxxxx.XxxxxXxxxxandroid/files/item.cblite2/db.sqlite3) - 
03-16 11:08:35.890 W/HardwareRenderer(15994): EGL error: EGL_BAD_SURFACE
03-16 11:08:35.900 W/HardwareRenderer(15994): Mountain View, we've had a problem here. Switching back to software rendering.
03-16 11:08:35.920 D/qdgralloc(15994): Invalid gralloc handle (at 0x0): ver(-1/12) ints(-1/12) fds(-1/2)magic(????/gmsm)
03-16 11:08:35.920 W/GraphicBufferMapper(15994): lock(...) failed -22 (Invalid argument)
03-16 11:08:35.920 W/Surface (15994): failed locking buffer (handle = 0x0)
03-16 11:08:35.920 E/ViewRootImpl(15994): Could not lock surface
03-16 11:08:35.920 E/ViewRootImpl(15994): java.lang.IllegalArgumentException
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Surface.nativeLockCanvas(Native Method)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Surface.lockCanvas(Surface.java:254)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2431)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2405)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2249)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5608)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Choreographer.doFrame(Choreographer.java:544)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.os.Handler.handleCallback(Handler.java:733)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.os.Looper.loop(Looper.java:136)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at android.app.ActivityThread.main(ActivityThread.java:5095)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
03-16 11:08:35.920 E/ViewRootImpl(15994): 	at dalvik.system.NativeStart.main(Native Method)
```

[20180316ReplicationError.txt](https://github.com/couchbase/couchbase-lite-net/files/1818861/20180316ReplicationError.txt)

**Comment by snej** [comment] 2018-03-16 16:35
SQLite error 14 is `SQLITE_CANTOPEN`, which is pretty generic … fortunately the errno value is hidden in the message: 14, `EFAULT` (“Bad address”). Wow. I don’t think I’ve ever run into this errno before; I believe it means a bad pointer was passed to a system call, in this case `open`.

The rest of your log looks like something bad happening in OpenGL, unrelated to us.

**Comment by snej** [comment] 2018-03-16 17:00
The errno is actually 24, `EMFILE`, "Too many open files". Your process has opened too many file descriptors, for some reason. SQLite is being very unhelpful about reporting the error, apparently. Did your application get any error/exception, or was it just the log messages?

**Comment by djpongh** [comment] 2018-03-16 18:09
@snej could we be leaking file descriptors?

**Comment by snej** [comment] 2018-03-16 18:44
It's possible, but I'd be surprised it hadn't shown up in unit or functional testing since we run hundreds of replications in a single process. I could try running the tests under `ulimit` to lower the max, or use `lsof` at the end of the tests to see how many FDs are open.

**Comment by borrrden** [comment] 2018-03-16 21:36
We had a problem with `EMFILE` before, but that was resolved (it has to do with blobs).  @thomas1983 Do these documents have attachments?

**Comment by thomas1983** [comment] 2018-03-19 07:03
Thanks guys for looking into it!

@borrrden, no they don't have blobs or attachments. @snej If the cause is that there are too many files open, how can I prevent this?  Just the log errors. As if the replication is in a loop, it is still trying but the error keeps coming up.

**Comment by snej** [comment] 2018-03-20 05:02
I've found that it's possible for lots of blobs to be open at once while pulling a database. I can fix this in LiteCore by lowering the parallelism, i.e. the number of docs being pulled at once.

**Comment by snej** [comment] 2018-03-20 05:13
I filed couchbase/couchbase-lite-net#996 to track fixing this.

**Comment by snej** [comment] 2018-03-20 18:12
This can be closed as soon as CBL-.NET is updated to the latest LiteCore.

**Closed** 2018-03-21 02:50 UTC
Labels: P1: high, ready

**Comment by thomas1983** [comment] 2018-03-22 08:47
Hi,

still cruising on
SGW 2.00 Beta2 (823)
CBL 2 beta (db023)
CBS 5.5

So, we are in the middle of sequential replication where we start one replication after the other is done. This works very well for very small buckets but it crashes after a couple of replication.

I've built the dll from the current master branch. But the problem still persists

It just returns to the android homescreen in the middle of a replication without any form of error or other notice.

The logcat gives me:

    03-22 09:12:34.599: I/[Replication:search](14582): SEARCH (False/PushAndPull) changed: 54/500 status:Busy					
    03-22 09:12:35.216: I/[Replication:search](14582): SEARCH (False/PushAndPull) changed: 55/500 status:Busy					
    03-22 09:12:35.320: I/[Replication:search](14582): SEARCH (False/PushAndPull) changed: 158/500 status:Busy					
    03-22 09:12:36.966: I/WindowState(556): WIN DEATH: Window{308d2a83 u0 com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity}				
    03-22 09:12:36.968: W/InputDispatcher(556): channel 'adc6f2e com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9					
    03-22 09:12:36.968: E/InputDispatcher(556): channel 'adc6f2e com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!					
    03-22 09:12:36.974: I/WindowState(556): WIN DEATH: Window{adc6f2e u0 com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity}				
    03-22 09:12:36.974: W/InputDispatcher(556): Attempted to unregister already unregistered input channel 'adc6f2e com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity (server)'					
    03-22 09:12:36.981: W/SurfaceFlinger(174): couldn't log to binary event log: overflow.					
    03-22 09:12:37.029: I/Zygote(199): Process 14582 exited due to signal (11)					
    03-22 09:12:37.068: I/ActivityManager(556): Process com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid (pid 14582) has died					
    03-22 09:12:37.069: W/ActivityManager(556): Force removing ActivityRecord{22f82ffc u0 com.mobile.xxxxxxxxxxxxx.xxxxxxxxxxxxxandroid/md5833b50a1e1772477f5c624e1ed573028.MainActivity t15595}: app died, no saved state					
    03-22 09:12:37.163: W/SurfaceFlinger(174): couldn't log to binary event log: overflow.					
    03-22 09:12:37.237: D/AndroidRuntime(15754): >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<		


The Sync Gateway Log gives

    2018-03-22T09:13:05.754+01:00 SyncMsg: [191ea519] #002: Type:subChanges Since:432 BatchSize:500  User:xxx				
    2018-03-22T09:13:05.754+01:00 Sync: [191ea519] Sending changes since 432. User:xxx				
    2018-03-22T09:13:05.754+01:00 Changes+: Int sequence multi changes feed...				
    2018-03-22T09:13:05.755+01:00 Changes: MultiChangesFeed(channels: {*}, options: {Since:432 Limit:0 Conflicts:false IncludeDocs:false Wait:false Continuous:false Terminator:0xc046b38120 HeartbeatMs:0 TimeoutMs:0 ActiveOnly:false}) ...   (to xxx)				
    2018-03-22T09:13:05.755+01:00 Changes+: MultiChangesFeed: channels expand to "!:1,*:5" ...   (to xxx)				
    2018-03-22T09:13:05.755+01:00 Cache: getCachedChanges("!", 432) --> 0 changes valid from #1				
    2018-03-22T09:13:05.755+01:00 Changes+: [changesFeed] Found 0 changes for channel !				
    2018-03-22T09:13:05.755+01:00 Changes+: [changesFeed] Found 0 changes for channel *				
    2018-03-22T09:13:05.755+01:00 Changes: MultiChangesFeed done   (to xxx)				
    2018-03-22T09:13:05.755+01:00 Sync+: [191ea519]     Sending 0 changes. User:xxx				
    2018-03-22T09:13:05.755+01:00 Sync: [191ea519] Sent all changes to client. User:xxx				
    2018-03-22T09:13:05.755+01:00 SyncMsg+: [191ea519] #002: Type:subChanges   --> Time:994.6µs User:xxx 				
    2018-03-22T09:13:05.778+01:00 HTTP+: [357be8f8] #022:    --> BLIP+WebSocket connection closed				
    2018-03-22T09:13:05.779+01:00 SyncMsg: [191ea519] #003: Type:proposeChanges #Changes: 0 User:xxx				
    2018-03-22T09:13:05.779+01:00 SyncMsg+: [191ea519] #003: Type:proposeChanges   --> OK Time:0s User:xxx 				
    2018-03-22T09:13:05.891+01:00 HTTP+: [39a2ffba] #027:    --> BLIP+WebSocket connection closed				
    2018-03-22T09:13:05.973+01:00 HTTP+: [191ea519] #023:    --> BLIP+WebSocket connection closed				
    2018-03-22T09:13:06.013+01:00 HTTP+: [12c4713f] #028:    --> BLIP+WebSocket connection closed				
    2018-03-22T09:13:06.051+01:00 HTTP+: [7850c56b] #026:    --> BLIP+WebSocket connection closed				

I think it has something to do with:

    Consumer closed input channel or an error occurred. 
    Channel is unrecoverably broken and will be disposed!	

It has something to do with too much threads

>  1) Basically this Errors occurs couple of times if your running number of process at a time in single thread . This is like a Deadlock situation.So any Scheduled tasks are there make it Synchronized particular burden objects. 2) Kill the unused processes at the time of Burden happens on MainThread.

**Comment by borrrden** [comment] 2018-03-22 08:51
This doesn't appear to be the same issue.  Please file a new one with the appropriate details.  This may be difficult, but this information does not provide very much about what is going on.  Try enabling text logging to see if there are any warnings (Support.Droid.EnableTextLogging()) in logcat.  Provide a reproduction project if possible.  Also you say you "built the dll from the master branch" but did you also build libLiteCore.so?  That is where the actual fix to this issue went.

**Comment by thomas1983** [comment] 2018-03-22 08:52
Yes I did. I'll try to do my best and file a new one. Thanks for your patience
