### ISSUE TITLE
v1.3 Unauthorized http state not reported on replicators LastError property

### ISSUE THREAD

**Issue by Steven-Mark-Ford** [couchbase/couchbase-lite-net#716] opened 2016-08-18 14:42 UTC
If I try replicate on a device which is not authorized to access a specific pull endpoint it does not report this on the LastError property on the replicator object where as this was previously report on CB 1.1.2 

Instead the following is just logged as a warning and the pullState remains in a "stopped" state:
Couchbase Tag: SYNC (RemoteSession) Message: Http Message failed to send, or got error response, passing to callback... : android.runtime.JavaProxyThrowable: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> [HttpResponseException: StatusCode = Unauthorized]

**Comment by borrrden** [comment] 2016-08-22 21:23
Can you show sample code of how you are checking?  Are you using the `Changed` event?

**Comment by borrrden** [comment] 2016-08-22 21:33
Also this looks like a duplicate of #703 which I have not been able to reproduce yet.  If I can reproduce this soon I will recommend an inclusion of the fix into 1.3.1

**Comment by Steven-Mark-Ford** [comment] 2016-08-23 08:06
Yes in the Changed event:
`public void CBReplicationChanged(object sender, ReplicationChangeEventArgs args)
{

Replication rep = sender as Replication;

if (rep != null)
{
    CheckForUnauthorisedCBUser(rep.LastError);
}
}
`
In previous versions LastError would be an HttpResponseException where StatusCode == HttpStatusCode.Unauthorized but in 1.3 this error never reaches the CBReplicationChanged event

**Comment by borrrden** [comment] 2016-08-23 23:57
Check `args.LastError` instead, it is more reliable.  That being said I have a unit test called `TestPullReplicationWithUsername` that I ran to check this.  The test itself doesn't verify the error but I verified it manually and received the expected exception in both `args.LastError` and `sender.LastError` so there must be something different about yours.  Do you think you can make a reproduction case?

**Comment by borrrden** [comment] 2016-08-24 00:02
Ok weird, I see this happening on the release nuget, but not from source.

**Comment by borrrden** [comment] 2016-08-24 00:13
Ok I found the issue!  I don't know why the unit test is working but...the change tracker is not reporting non-transient errors back to the replicator.  It's a small change, and a regression, and so I will recommend it for 1.3.1 which is set to come out in a few weeks (you can grab a CI build as well before the official release if it gets approved).  There is not much in 1.3.1 at the moment.

**Closed** 2016-08-24 00:34 UTC
Labels: bug, size-small

**Comment by Steven-Mark-Ford** [comment] 2016-08-24 03:56
Thanks! Glad you found it.
