### ISSUE TITLE
Unauthorized 401 after successful OpenID Connect login

### ISSUE THREAD

**Issue by tura08** [couchbase/couchbase-lite-net#917] opened 2017-10-13 06:22 UTC
**Version**: 1.4.1-b0106
**Device**: Moto G5 Plus
**OS**: Android 7.1

We are facing an annoying issue where, after a fresh deploy of our app, after successful login using OpenID Connect, replicators throw LastError = HttpResponseException where StatusCode = Unauthorized (401). After quitting the app and starting again a few times, the issue goes away and we are able to sync documents.

You can see that it logs in properly:

> [0:] INFO) SYNC (OpenIDAuthenticator): [16] 2017-10-13 01:57:00.619+08:00 OpenIDAuthenticator[https://server/db/]: logged in as [username]
[0:] INFO) SYNC (OpenIDAuthenticator): [7] 2017-10-13 01:57:00.678+08:00 OpenIDAuthenticator[https://server/db/] saved ID token to storage
[0:] INFO) SYNC (RemoteLogin): [16] 2017-10-13 01:57:00.682+08:00 Couchbase.Lite.Auth.RemoteLogin successfully logged in!
[0:] INFO) SYNC (Replication): [10] 2017-10-13 01:57:00.690+08:00 Puller 65c610da-edff-4612-a387-2910ef632e3b successfully logged in!

But soon after:

> [0:] INFO) CHANGE TRACKER (SocketChangeTracker): [16] 2017-10-13 01:57:00.895+08:00 Stopping SocketChangeTracker[db/]...
[0:] INFO) SYNC (Puller): [14] 2017-10-13 01:57:00.910+08:00 Change tracker for 65c610da-edff-4612-a387-2910ef632e3b stopped; error=[HttpResponseException: StatusCode = Unauthorized]
[0:] INFO) SYNC (Replication): [16] 2017-10-13 01:57:00.916+08:00 Error set during replication (application may continue):
[HttpResponseException: StatusCode = Unauthorized]

[stack.txt](https://github.com/couchbase/couchbase-lite-net/files/1381559/stack.txt)

**Comment by borrrden** [comment] 2017-10-13 21:41
What version of Sync Gateway?

**Comment by tura08** [comment] 2017-10-14 03:07
The docker image tagged as 1.4.0-2

**Comment by tura08** [comment] 2017-10-16 03:49
Any ideas?

**Comment by tura08** [comment] 2017-10-16 07:19
I upgraded to the next SG version (1.4.1-3) and its working now.

**Comment by tura08** [comment] 2017-10-16 08:17
Actually this is still an issue. Once in a blue moon it goes through.

**Comment by borrrden** [comment] 2017-10-16 08:23
Can you post a session with Couchbase lite logs and sync gateway logs for the same period?

**Comment by borrrden** [comment] 2017-10-16 21:56
Also, can you post the config file you are using (without the access keys)?

**Comment by borrrden** [comment] 2017-10-16 23:35
I realize I didn't post a comment about this that I was thinking.  The logs show that there is a 401 from the initial challenge, which is weird...It means that the challenge failed so the replication never got a valid session.

**Comment by tura08** [comment] 2017-10-17 01:28
Good point, yes that is strange. Logs attached. 

[cbl_log.txt](https://github.com/couchbase/couchbase-lite-net/files/1389468/cbl_log.txt)
[sg_log.txt](https://github.com/couchbase/couchbase-lite-net/files/1389469/sg_log.txt)
[config.txt](https://github.com/couchbase/couchbase-lite-net/files/1389470/config.txt)

**Comment by borrrden** [comment] 2017-10-17 01:40
Are you using any proxies or load balancers?  It looks like the web socket response is getting messed with and so the replicator is falling back to non-web socket mode.  The ultimate issue is that it doesn't seem to reuse the auth credentials when it does so, but you can test out a workaround but setting `UseWebSocket` in the replication options to `false`.

**Comment by tura08** [comment] 2017-10-17 01:46
We have an nginx load balancer in front of 3 sync gateway servers. We have another nginx at the front for reverse proxying. I'm also still getting the issue where the callback url has http in it rather than https. I'll look into our proxy settings.

**Comment by borrrden** [comment] 2017-10-17 01:48
If the callback URL is not correct, you can try [overriding it](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/config-properties/index.html#1.4/databases-foo_db-oidc-providers-foo_provider-callback_url)

**Comment by tura08** [comment] 2017-10-17 02:14
Still have issue after overriding url to https and setting UseWebSocket = false

**Comment by borrrden** [comment] 2017-10-17 02:16
Can you test a setup without the nginx instances?  They sometimes remove header values and break things in unexpected ways.  It looks like the first changes feed request in the logs was authenticated correctly, but the subsequent one was not.

**Comment by tura08** [comment] 2017-10-17 03:32
Ok, yes there was a problem with nginx config. My bad; we were not setting the following field in nginx config:

```    
proxy_set_header    Upgrade $http_upgrade;
proxy_set_header    Connection "upgrade";
```

**Comment by tura08** [comment] 2017-10-17 03:39
Although I am able to login now (puller stops on one-shot replication), still getting Unauthorized.

**Comment by tura08** [comment] 2017-10-17 04:25
It seems like it tries to replicate but just can't get there.

[cbl_logs_websocket.txt](https://github.com/couchbase/couchbase-lite-net/files/1389752/cbl_logs_websocket.txt)

**Comment by tura08** [comment] 2017-10-17 08:37
Seems to be only an issue with the puller. I can push documents, but puller is getting Unauthorized.

**Comment by tura08** [comment] 2017-10-17 08:49
I looked at a session that was just created, and the expiration time seems to have already past - ergo Unauthorized.

`{
  "id": "eeef14193750728162ce7d0a892577af62929fc0",
  "username": "username",
  "expiration": "2017-10-17T08:48:35.000008442Z",
  "ttl": 299378100486
}`

**Comment by borrrden** [comment] 2017-10-17 09:58
Thanks for all the information.  I have to do OpenID testing for 1.4.1 anyway so I will try it out and see if I can get the same thing to happen.  I recently tested 1.4.1 and it worked alright but maybe I will set up a more permanent example using Sync Gateway's test auth provider.

In the meantime if this keeps not working you could try using implicit auth instead of automatic (which is that you set up an OpenID provider of your own which will perform the auth, and then create a session in sync gateway which you can then return and set in the replication).  That should have a lot fewer problems than automatic auth.

**Comment by tura08** [comment] 2017-10-18 00:33
Thanks, yeah I'll try that for now.

**Comment by borrrden** [comment] 2017-10-18 23:49
Could you provide your activity for handling the actual login for the OpenID Provider (i.e. the part that shows the "webpage" to log in with credentials)?  The way I did it when we first wrote the provider is no longer valid and honestly OpenID is now even more complicated for Xamarin.  From what I read now you need to use a custom URL for callback, and not HTTP or HTTPS.

**Comment by tura08** [comment] 2017-10-19 00:43
I can, but I'm using the code from your openid-sample branch so it will be the same. 
Regarding callback URL, the issue is that embedded web views are no longer considered secure, because they provide access to cookies etc. It is therefore recommended to use the native UI now, Custom Tabs on Android and SFSafariViewController on iOS, which block access to such things and are much more secure. With these implementations, you have too use app linking and so traditional http or https callback URLs don't work. These implementations don't work on older OS versions, so you would have to fall back to web view sometimes. Additionally, if your app uses Google Auth, you have to use Custom Tabs now as Google block access via web views for security reasons. For Auth, I'm currently using Xamarin.Auth. They have some [comments ](https://github.com/xamarin/Xamarin.Auth#312-native-ui)here about native ui.

**Comment by borrrden** [comment] 2017-10-19 00:55
I tried using Xamarin Auth but it continuously frustrated me.  I finally got things working manually but I am able to log in correctly.  Sometimes I see the same exceptions but after that things keep going.  Once I tidy up this new sample I am going to post it somewhere and delete the awful misleading openid-sample branch because at this point it's only half good.

**Comment by borrrden** [comment] 2017-10-19 01:19
I'm pretty sure I've found the issue here and it looks like a recent regression from when I fixed another issue dealing with a functional test failure.  The result is that the cookie received from the login procedure was not being used.  The fix is quite simple though, it seems.  The web socket change tracker handles cookies separately so it will succeed while other HTTP requests will fail.

**Comment by borrrden** [comment] 2017-10-19 01:32
I'm closing this so it can link with the commit, but if things don't improve then let me know.

**Closed** 2017-10-19 01:32 UTC

**Comment by tura08** [comment] 2017-10-19 02:07
Ok, I'll test once it up on the CI server. Thanks!

**Comment by tura08** [comment] 2017-10-19 02:21
Works!
